#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


# python manage.py migrate --settings config.settings.local
# python manage.py collectstatic --settings config.settings.local
python manage.py runserver 0.0.0.0:8000 --settings config.settings.local
# gunicorn config.wsgi:application --bind 0.0.0.0:8000
