# Generated by Django 3.2.12 on 2022-03-05 00:06

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emailing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteEmailsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8000)),
            ],
            options={
                'verbose_name': 'Emails by website',
                'db_table': 'website_emails_type',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='WebsiteLegalPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=8000)),
                ('slug', models.CharField(max_length=8000, null=True)),
                ('content', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'Legal website pages',
                'db_table': 'website_pages_legals',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='WebsiteEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_default_title', models.BooleanField(default=False)),
                ('use_default_introduction', models.BooleanField(default=False)),
                ('use_default_despedida', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=99999)),
                ('introduction', models.TextField()),
                ('despedida', models.TextField()),
                ('content', ckeditor.fields.RichTextField()),
                ('default_despedida', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='emailing.newsletterdefaultdespedida')),
                ('default_introduction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='emailing.newsletterdefaultintroduction')),
                ('default_title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='emailing.newsletterdefaulttitle')),
                ('type_related', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.websiteemailstype')),
            ],
            options={
                'verbose_name': 'Emails by website',
                'db_table': 'website_emails',
                'ordering': ['-id'],
            },
        ),
    ]
