# Generated by Django 3.2.12 on 2022-03-09 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteemail',
            name='date_to_send',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='websiteemail',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
