# Generated by Django 3.2.12 on 2022-03-12 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emailing', '0004_auto_20220310_0534'),
        ('web', '0002_auto_20220309_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websiteemail',
            name='default_despedida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='emailing.newsletterdefaultdespedida'),
        ),
        migrations.AlterField(
            model_name='websiteemail',
            name='default_introduction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='emailing.newsletterdefaultintroduction'),
        ),
        migrations.AlterField(
            model_name='websiteemail',
            name='default_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='emailing.newsletterdefaulttitle'),
        ),
    ]
