# Generated by Django 3.2.12 on 2022-03-14 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20220313_0511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websiteemailtrack',
            name='email_related',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_related', to='web.websiteemail'),
        ),
    ]
