# Generated by Django 3.2.12 on 2022-05-26 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('escritos', '0005_auto_20220512_1656'),
        ('empresas', '0005_auto_20220513_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='Key',
            fields=[
                ('ip', models.CharField(blank=True, max_length=50, null=True)),
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Key')),
                ('in_use', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('removed', models.DateTimeField(blank=True, verbose_name='Removed')),
                ('limit', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_key', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Key',
                'verbose_name_plural': 'Keys',
                'db_table': 'api_keys',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='TermRequestAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('path', models.CharField(max_length=500)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.key')),
                ('search', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='escritos.term')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Term requested',
                'verbose_name_plural': 'Terms requested',
                'db_table': 'api_terms_requested',
            },
        ),
        migrations.CreateModel(
            name='ReasonKeyRequested',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('description', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reason for requesting Key',
                'verbose_name_plural': 'Reason for requesting Key',
                'db_table': 'api_reason_key',
            },
        ),
        migrations.CreateModel(
            name='CompanyRequestAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('path', models.CharField(max_length=500)),
                ('is_excel', models.BooleanField(default=False)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.key')),
                ('search', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empresas.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company requested',
                'verbose_name_plural': 'Companies requested',
                'db_table': 'api_companies_requested',
            },
        ),
    ]
