# Generated by Django 3.2.12 on 2022-05-27 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndpointsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Endpoints category',
                'verbose_name_plural': 'Endpoints categories',
                'db_table': 'api_endpoints_categories',
            },
        ),
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250)),
                ('slug', models.CharField(blank=True, max_length=250)),
                ('url', models.CharField(blank=True, max_length=250)),
                ('description', models.TextField(blank=True)),
                ('url_example', models.CharField(blank=True, max_length=250)),
                ('response_example', models.JSONField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_premium', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('is_deprecated', models.BooleanField(default=False)),
                ('version', models.CharField(blank=True, default='v1', max_length=3)),
                ('date_deprecated', models.DateTimeField(blank=True)),
                ('price', models.IntegerField(default=0)),
                ('title_related', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.endpointscategory')),
            ],
            options={
                'verbose_name': 'Endpoint',
                'verbose_name_plural': 'Endpoints',
                'db_table': 'api_endpoints',
            },
        ),
    ]
