# Generated by Django 3.2.12 on 2022-05-28 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_endpoint_endpointscategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='removed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Removed'),
        ),
    ]
