# Generated by Django 3.2.12 on 2022-06-16 20:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_key_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='response_example',
            field=ckeditor.fields.RichTextField(blank=True, default=''),
        ),
    ]
