# Generated by Django 3.2.12 on 2022-06-18 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('super_investors', '0007_auto_20220612_2300'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_alter_endpoint_response_example'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperinvestorRequestAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('path', models.CharField(max_length=500)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.key')),
                ('search', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='super_investors.superinvestor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Superinvestor requested',
                'verbose_name_plural': 'Superinvestors requested',
                'db_table': 'api_superinvestor_requested',
            },
        ),
    ]
