# Generated by Django 3.2.12 on 2022-06-25 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_superinvestorrequestapi'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='response_example_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
