# Generated by Django 3.2.12 on 2022-03-05 00:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
                ('opened', models.BooleanField(default=False)),
                ('date_opened', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Email from notifications',
                'db_table': 'emails_notifications',
            },
        ),
        migrations.CreateModel(
            name='EmailPublicBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
                ('opened', models.BooleanField(default=False)),
                ('date_opened', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Email from public blog',
                'db_table': 'emails_public_blog',
            },
        ),
        migrations.CreateModel(
            name='EmailWebsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
                ('opened', models.BooleanField(default=False)),
                ('date_opened', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Email from public blog',
                'db_table': 'emails_website',
            },
        ),
        migrations.CreateModel(
            name='NewsletterDefaultDespedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('times_used', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Default despedida',
                'db_table': 'newsletters_default_despedidas',
                'ordering': ['times_used'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterDefaultIntroduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('times_used', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Default intro',
                'db_table': 'newsletters_default_intro',
                'ordering': ['times_used'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterDefaultTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('times_used', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Default title',
                'db_table': 'newsletters_default_titles',
                'ordering': ['times_used'],
            },
        ),
        migrations.CreateModel(
            name='WritterNewsletterDefaultOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_despedidas', models.ManyToManyField(blank=True, to='emailing.NewsletterDefaultDespedida')),
                ('default_introductions', models.ManyToManyField(blank=True, to='emailing.NewsletterDefaultIntroduction')),
                ('default_titles', models.ManyToManyField(blank=True, to='emailing.NewsletterDefaultTitle')),
                ('writter', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Opciones por defecto',
                'db_table': 'newsletters_default_options',
                'ordering': ['id'],
            },
        ),
    ]
