# Generated by Django 3.2.12 on 2022-03-10 05:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emailing', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletterdefaultdespedida',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='newsletterdefaultintroduction',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
