# Generated by Django 3.2.12 on 2022-03-13 00:53

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emailing', '0004_auto_20220310_0534'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletterdefaultdespedida',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsletterdefaultdespedida',
            name='in_use',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='newsletterdefaultintroduction',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsletterdefaultintroduction',
            name='in_use',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='newsletterdefaulttitle',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsletterdefaulttitle',
            name='in_use',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='newsletterdefaulttitle',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='writternewsletterdefaultoptions',
            name='writter',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='writter_default_options', to=settings.AUTH_USER_MODEL),
        ),
    ]
