# Generated by Django 3.2.12 on 2022-03-13 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
        ('emailing', '0005_auto_20220313_0053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailwebsite',
            name='email_related',
        ),
        migrations.RemoveField(
            model_name='emailwebsite',
            name='sent_to',
        ),
        migrations.AlterField(
            model_name='emailnotification',
            name='email_related',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='general.notification'),
        ),
        migrations.DeleteModel(
            name='EmailPublicBlog',
        ),
        migrations.DeleteModel(
            name='EmailWebsite',
        ),
    ]
