# Generated by Django 3.2.12 on 2022-03-17 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public_blog', '0009_auto_20220317_1106'),
        ('web', '0007_auto_20220317_1106'),
        ('emailing', '0007_alter_emailnotification_email_related'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writternewsletterdefaultoptions',
            name='default_despedidas',
        ),
        migrations.RemoveField(
            model_name='writternewsletterdefaultoptions',
            name='default_introductions',
        ),
        migrations.RemoveField(
            model_name='writternewsletterdefaultoptions',
            name='default_titles',
        ),
        migrations.RemoveField(
            model_name='writternewsletterdefaultoptions',
            name='writter',
        ),
        migrations.DeleteModel(
            name='EmailNotification',
        ),
        migrations.DeleteModel(
            name='NewsletterDefaultDespedida',
        ),
        migrations.DeleteModel(
            name='NewsletterDefaultIntroduction',
        ),
        migrations.DeleteModel(
            name='NewsletterDefaultTitle',
        ),
        migrations.DeleteModel(
            name='WritterNewsletterDefaultOptions',
        ),
    ]
