# Generated by Django 3.2.12 on 2022-04-15 00:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general', '0003_auto_20220415_0001'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('horizon', models.IntegerField(blank=True, choices=[(1, 'Long Term'), (2, 'Medium Term'), (3, 'Short Term')], null=True)),
                ('risk_profile', models.IntegerField(blank=True, choices=[(1, 'PROFILE VERY AGRESIVE'), (2, 'PROFILE AGRESIVE'), (3, 'PROFILE CONSERVATIVE'), (4, 'PROFILE VERY CONSERVATIVE'), (5, 'PROFILE REGULAR')], null=True)),
                ('investor_type', models.IntegerField(blank=True, choices=[(1, 'Activo'), (2, 'Intermedio'), (3, 'Pasivo'), (4, 'Especulador')], null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_investor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User investor profile',
                'db_table': 'user_investor_profile',
            },
        ),
        migrations.CreateModel(
            name='TemporaryInvestorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('horizon', models.IntegerField(blank=True, choices=[(1, 'Long Term'), (2, 'Medium Term'), (3, 'Short Term')], null=True)),
                ('risk_profile', models.IntegerField(blank=True, choices=[(1, 'PROFILE VERY AGRESIVE'), (2, 'PROFILE AGRESIVE'), (3, 'PROFILE CONSERVATIVE'), (4, 'PROFILE VERY CONSERVATIVE'), (5, 'PROFILE REGULAR')], null=True)),
                ('investor_type', models.IntegerField(blank=True, choices=[(1, 'Activo'), (2, 'Intermedio'), (3, 'Pasivo'), (4, 'Especulador')], null=True)),
                ('profile_related', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temporary_investor', to='roboadvisor.investorprofile')),
            ],
            options={
                'verbose_name': 'Temporary investor profile',
                'db_table': 'temporary_investor_profile',
            },
        ),
        migrations.CreateModel(
            name='RoboAdvisorService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveBigIntegerField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
                ('available', models.BooleanField(default=True)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.CharField(blank=True, max_length=500, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='general.category')),
                ('tags', models.ManyToManyField(blank=True, to='general.Tag')),
            ],
            options={
                'verbose_name': 'Roboadvisor services',
                'db_table': 'roboadvisor_services',
                'ordering': ['-order'],
            },
        ),
    ]
