# Generated by Django 3.2.12 on 2022-05-01 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roboadvisor', '0002_auto_20220429_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roboadvisorquestioncompanyanalysis',
            name='result',
            field=models.IntegerField(blank=True, choices=[(1, 'Comprar'), (2, 'Vender'), (3, 'Mantener'), (4, 'Error')], null=True),
        ),
        migrations.AlterField(
            model_name='roboadvisoruserserviceactivity',
            name='status',
            field=models.CharField(choices=[('finished', 'Finished'), ('abandoned', 'Abandoned'), ('started', 'Started'), ('not-payed', 'Not payed')], default='started', max_length=500),
        ),
        migrations.AlterField(
            model_name='roboadvisoruserservicestepactivity',
            name='status',
            field=models.CharField(choices=[('finished', 'Finished'), ('abandoned', 'Abandoned'), ('started', 'Started'), ('not-payed', 'Not payed')], default='started', max_length=500),
        ),
    ]
