# Generated by Django 3.2.12 on 2022-04-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roboadvisor', '0002_auto_20220415_1924'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoboAdvisorServiceStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.CharField(blank=True, max_length=500, null=True)),
                ('date_started', models.DateTimeField(auto_now_add=True)),
                ('date_finished', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, choices=[(1, 'Finished'), (2, 'Abandoned'), (3, 'Asked'), (4, 'Skiped')], null=True)),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Roboadvisor service step',
                'db_table': 'roboadvisor_service_steps',
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='roboadvisorservice',
            options={'ordering': ['order'], 'verbose_name': 'Roboadvisor service'},
        ),
        migrations.RemoveField(
            model_name='roboadvisorquestioncompanyanalysis',
            name='date_finished',
        ),
        migrations.RemoveField(
            model_name='roboadvisorquestioncompanyanalysis',
            name='date_started',
        ),
        migrations.RemoveField(
            model_name='roboadvisorquestioncompanyanalysis',
            name='status',
        ),
        migrations.RemoveField(
            model_name='roboadvisorquestionfinancialsituation',
            name='date_finished',
        ),
        migrations.RemoveField(
            model_name='roboadvisorquestionfinancialsituation',
            name='date_started',
        ),
        migrations.RemoveField(
            model_name='roboadvisorquestionfinancialsituation',
            name='status',
        ),
        migrations.RemoveField(
            model_name='roboadvisorquestionhorizon',
            name='date_finished',
        ),
        migrations.RemoveField(
            model_name='roboadvisorquestionhorizon',
            name='date_started',
        ),
        migrations.RemoveField(
            model_name='roboadvisorquestionhorizon',
            name='status',
        ),
        migrations.RemoveField(
            model_name='roboadvisorquestioninvestorexperience',
            name='date_finished',
        ),
        migrations.RemoveField(
            model_name='roboadvisorquestioninvestorexperience',
            name='date_started',
        ),
        migrations.RemoveField(
            model_name='roboadvisorquestioninvestorexperience',
            name='status',
        ),
        migrations.RemoveField(
            model_name='roboadvisorquestionportfolioassetsweight',
            name='date_finished',
        ),
        migrations.RemoveField(
            model_name='roboadvisorquestionportfolioassetsweight',
            name='date_started',
        ),
        migrations.RemoveField(
            model_name='roboadvisorquestionportfolioassetsweight',
            name='status',
        ),
        migrations.RemoveField(
            model_name='roboadvisorquestionriskaversion',
            name='date_finished',
        ),
        migrations.RemoveField(
            model_name='roboadvisorquestionriskaversion',
            name='date_started',
        ),
        migrations.RemoveField(
            model_name='roboadvisorquestionriskaversion',
            name='status',
        ),
        migrations.RemoveField(
            model_name='roboadvisorquestionstocksportfolio',
            name='date_finished',
        ),
        migrations.RemoveField(
            model_name='roboadvisorquestionstocksportfolio',
            name='date_started',
        ),
        migrations.RemoveField(
            model_name='roboadvisorquestionstocksportfolio',
            name='status',
        ),
        migrations.AddField(
            model_name='roboadvisorservice',
            name='steps',
            field=models.ManyToManyField(blank=True, to='roboadvisor.RoboAdvisorServiceStep'),
        ),
    ]
