# Generated by Django 3.2.12 on 2022-04-18 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('roboadvisor', '0006_auto_20220416_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoboAdvisorUserTestActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_started', models.DateTimeField(auto_now_add=True)),
                ('date_finished', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Finished'), (2, 'Abandoned'), (3, 'Asked'), (4, 'Skiped')])),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='roboadvisor.roboadvisorservice')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'RoboAdvisor Test Activity',
                'verbose_name_plural': 'RoboAdvisor Tests Activity',
                'db_table': 'roboadvisor_test_activity',
            },
        ),
        migrations.CreateModel(
            name='RoboAdvisorUserTestStepActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='roboadvisor.roboadvisorusertestactivity')),
                ('service_step', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='roboadvisor.roboadvisorservicestep')),
            ],
            options={
                'verbose_name': 'RoboAdvisor Test Step Activity',
                'verbose_name_plural': 'RoboAdvisor Test Steps Activity',
                'db_table': 'roboadvisor_test_steps_activity',
            },
        ),
        migrations.AddField(
            model_name='roboadvisorquestioncompanyanalysis',
            name='comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='roboadvisorquestioncompanyanalysis',
            name='horizon_period',
            field=models.PositiveIntegerField(choices=[(0, 'Minutos'), (1, 'Horas'), (2, 'Días'), (3, 'Semanas'), (4, 'Meses'), (5, 'Años')], default=4),
        ),
        migrations.AddField(
            model_name='roboadvisorquestioncompanyanalysis',
            name='horizon_time',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='roboadvisorquestionportfoliocomposition',
            name='comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='roboadvisorquestionportfoliocomposition',
            name='horizon_period',
            field=models.PositiveIntegerField(choices=[(0, 'Minutos'), (1, 'Horas'), (2, 'Días'), (3, 'Semanas'), (4, 'Meses'), (5, 'Años')], default=4),
        ),
        migrations.AddField(
            model_name='roboadvisorquestionportfoliocomposition',
            name='horizon_time',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='roboadvisorquestionriskaversion',
            name='comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='roboadvisorquestionriskaversion',
            name='horizon_period',
            field=models.PositiveIntegerField(choices=[(0, 'Minutos'), (1, 'Horas'), (2, 'Días'), (3, 'Semanas'), (4, 'Meses'), (5, 'Años')], default=4),
        ),
        migrations.AddField(
            model_name='roboadvisorquestionriskaversion',
            name='horizon_time',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='roboadvisorquestioncompanyanalysis',
            name='period_time_studied',
            field=models.PositiveIntegerField(choices=[(0, 'Minutos'), (1, 'Horas'), (2, 'Días'), (3, 'Semanas'), (4, 'Meses'), (5, 'Años')], default=4),
        ),
        migrations.AlterField(
            model_name='roboadvisorquestionportfoliocomposition',
            name='period_time_studied',
            field=models.PositiveIntegerField(choices=[(0, 'Minutos'), (1, 'Horas'), (2, 'Días'), (3, 'Semanas'), (4, 'Meses'), (5, 'Años')], default=4),
        ),
        migrations.DeleteModel(
            name='RoboAdvisorQuestionHorizon',
        ),
    ]
