# Generated by Django 3.2.12 on 2022-04-18 21:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('roboadvisor', '0007_auto_20220418_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roboadvisorquestioncompanyanalysis',
            name='service',
        ),
        migrations.RemoveField(
            model_name='roboadvisorquestioncompanyanalysis',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='roboadvisorquestionfinancialsituation',
            name='service',
        ),
        migrations.RemoveField(
            model_name='roboadvisorquestionfinancialsituation',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='roboadvisorquestioninvestorexperience',
            name='service',
        ),
        migrations.RemoveField(
            model_name='roboadvisorquestioninvestorexperience',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='roboadvisorquestionportfolioassetsweight',
            name='service',
        ),
        migrations.RemoveField(
            model_name='roboadvisorquestionportfolioassetsweight',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='roboadvisorquestionriskaversion',
            name='service',
        ),
        migrations.RemoveField(
            model_name='roboadvisorquestionriskaversion',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='roboadvisorquestionstocksportfolio',
            name='service',
        ),
        migrations.RemoveField(
            model_name='roboadvisorquestionstocksportfolio',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='roboadvisorservicestep',
            name='slug',
        ),
        migrations.AddField(
            model_name='roboadvisorquestioncompanyanalysis',
            name='date_finished',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roboadvisorquestioncompanyanalysis',
            name='date_started',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roboadvisorquestioncompanyanalysis',
            name='service_activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='roboadvisor.roboadvisorusertestactivity'),
        ),
        migrations.AddField(
            model_name='roboadvisorquestioncompanyanalysis',
            name='service_step',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='roboadvisor.roboadvisorservicestep'),
        ),
        migrations.AddField(
            model_name='roboadvisorquestioncompanyanalysis',
            name='status',
            field=models.IntegerField(choices=[(1, 'Finished'), (2, 'Abandoned'), (3, 'Started')], default=3),
        ),
        migrations.AddField(
            model_name='roboadvisorquestionfinancialsituation',
            name='date_finished',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roboadvisorquestionfinancialsituation',
            name='date_started',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roboadvisorquestionfinancialsituation',
            name='service_activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='roboadvisor.roboadvisorusertestactivity'),
        ),
        migrations.AddField(
            model_name='roboadvisorquestionfinancialsituation',
            name='service_step',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='roboadvisor.roboadvisorservicestep'),
        ),
        migrations.AddField(
            model_name='roboadvisorquestionfinancialsituation',
            name='status',
            field=models.IntegerField(choices=[(1, 'Finished'), (2, 'Abandoned'), (3, 'Started')], default=3),
        ),
        migrations.AddField(
            model_name='roboadvisorquestioninvestorexperience',
            name='date_finished',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roboadvisorquestioninvestorexperience',
            name='date_started',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roboadvisorquestioninvestorexperience',
            name='service_activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='roboadvisor.roboadvisorusertestactivity'),
        ),
        migrations.AddField(
            model_name='roboadvisorquestioninvestorexperience',
            name='service_step',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='roboadvisor.roboadvisorservicestep'),
        ),
        migrations.AddField(
            model_name='roboadvisorquestioninvestorexperience',
            name='status',
            field=models.IntegerField(choices=[(1, 'Finished'), (2, 'Abandoned'), (3, 'Started')], default=3),
        ),
        migrations.AddField(
            model_name='roboadvisorquestionportfolioassetsweight',
            name='date_finished',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roboadvisorquestionportfolioassetsweight',
            name='date_started',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roboadvisorquestionportfolioassetsweight',
            name='service_activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='roboadvisor.roboadvisorusertestactivity'),
        ),
        migrations.AddField(
            model_name='roboadvisorquestionportfolioassetsweight',
            name='service_step',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='roboadvisor.roboadvisorservicestep'),
        ),
        migrations.AddField(
            model_name='roboadvisorquestionportfolioassetsweight',
            name='status',
            field=models.IntegerField(choices=[(1, 'Finished'), (2, 'Abandoned'), (3, 'Started')], default=3),
        ),
        migrations.AddField(
            model_name='roboadvisorquestionriskaversion',
            name='date_finished',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roboadvisorquestionriskaversion',
            name='date_started',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roboadvisorquestionriskaversion',
            name='service_activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='roboadvisor.roboadvisorusertestactivity'),
        ),
        migrations.AddField(
            model_name='roboadvisorquestionriskaversion',
            name='service_step',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='roboadvisor.roboadvisorservicestep'),
        ),
        migrations.AddField(
            model_name='roboadvisorquestionriskaversion',
            name='status',
            field=models.IntegerField(choices=[(1, 'Finished'), (2, 'Abandoned'), (3, 'Started')], default=3),
        ),
        migrations.AddField(
            model_name='roboadvisorquestionstocksportfolio',
            name='date_finished',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roboadvisorquestionstocksportfolio',
            name='date_started',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roboadvisorquestionstocksportfolio',
            name='service_activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='roboadvisor.roboadvisorusertestactivity'),
        ),
        migrations.AddField(
            model_name='roboadvisorquestionstocksportfolio',
            name='service_step',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='roboadvisor.roboadvisorservicestep'),
        ),
        migrations.AddField(
            model_name='roboadvisorquestionstocksportfolio',
            name='status',
            field=models.IntegerField(choices=[(1, 'Finished'), (2, 'Abandoned'), (3, 'Started')], default=3),
        ),
        migrations.RemoveField(
            model_name='roboadvisorservicestep',
            name='service_related',
        ),
        migrations.AddField(
            model_name='roboadvisorservicestep',
            name='service_related',
            field=models.ManyToManyField(blank=True, related_name='steps', to='roboadvisor.RoboAdvisorService'),
        ),
        migrations.AlterField(
            model_name='roboadvisorusertestactivity',
            name='status',
            field=models.IntegerField(choices=[(1, 'Finished'), (2, 'Abandoned'), (3, 'Started')], default=3),
        ),
        migrations.DeleteModel(
            name='RoboAdvisorUserTestStepActivity',
        ),
    ]
