# Generated by Django 3.2.12 on 2022-04-18 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roboadvisor', '0008_auto_20220418_2126'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RoboAdvisorUserTestActivity',
            new_name='RoboAdvisorUserServiceActivity',
        ),
        migrations.AlterModelOptions(
            name='investorprofile',
            options={'verbose_name': 'User investor profile', 'verbose_name_plural': 'Users investor profiles'},
        ),
        migrations.AlterModelOptions(
            name='roboadvisorservice',
            options={'ordering': ['order'], 'verbose_name': 'Roboadvisor service', 'verbose_name_plural': 'Roboadvisor services'},
        ),
        migrations.AlterModelOptions(
            name='roboadvisorservicestep',
            options={'ordering': ['order'], 'verbose_name': 'Roboadvisor service step', 'verbose_name_plural': 'Roboadvisor service steps'},
        ),
        migrations.AlterModelOptions(
            name='roboadvisoruserserviceactivity',
            options={'verbose_name': 'RoboAdvisor Service Activity', 'verbose_name_plural': 'RoboAdvisor Service Activity'},
        ),
        migrations.AlterModelOptions(
            name='temporaryinvestorprofile',
            options={'verbose_name': 'Temporary investor profile', 'verbose_name_plural': 'Temporary investor profiles'},
        ),
        migrations.AlterModelTable(
            name='roboadvisoruserserviceactivity',
            table='roboadvisor_service_activity',
        ),
        migrations.CreateModel(
            name='RoboAdvisorUserServiceStepActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Finished'), (2, 'Abandoned'), (3, 'Started')], default=3)),
                ('date_started', models.DateTimeField(blank=True, null=True)),
                ('date_finished', models.DateTimeField(auto_now_add=True)),
                ('step', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='roboadvisor.roboadvisorservicestep')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'RoboAdvisor Service Step Activity',
                'verbose_name_plural': 'RoboAdvisor Service Steps Activity',
                'db_table': 'roboadvisor_service_step_activity',
            },
        ),
        migrations.AlterField(
            model_name='roboadvisorquestioncompanyanalysis',
            name='service_step',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='roboadvisor.roboadvisoruserservicestepactivity'),
        ),
        migrations.AlterField(
            model_name='roboadvisorquestionfinancialsituation',
            name='service_step',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='roboadvisor.roboadvisoruserservicestepactivity'),
        ),
        migrations.AlterField(
            model_name='roboadvisorquestioninvestorexperience',
            name='service_step',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='roboadvisor.roboadvisoruserservicestepactivity'),
        ),
        migrations.AlterField(
            model_name='roboadvisorquestionportfolioassetsweight',
            name='service_step',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='roboadvisor.roboadvisoruserservicestepactivity'),
        ),
        migrations.AlterField(
            model_name='roboadvisorquestionriskaversion',
            name='service_step',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='roboadvisor.roboadvisoruserservicestepactivity'),
        ),
        migrations.AlterField(
            model_name='roboadvisorquestionstocksportfolio',
            name='service_step',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='roboadvisor.roboadvisoruserservicestepactivity'),
        ),
    ]
