# Generated by Django 3.2.12 on 2022-04-19 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_auto_20220415_0001'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roboadvisor', '0009_auto_20220418_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='roboadvisorquestionfinancialsituation',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='general.currency'),
        ),
        migrations.AddField(
            model_name='roboadvisorquestionportfoliocomposition',
            name='date_finished',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roboadvisorquestionportfoliocomposition',
            name='date_started',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roboadvisorquestionportfoliocomposition',
            name='service_activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='roboadvisor.roboadvisoruserserviceactivity'),
        ),
        migrations.AddField(
            model_name='roboadvisorquestionportfoliocomposition',
            name='service_step',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='roboadvisor.roboadvisoruserservicestepactivity'),
        ),
        migrations.AddField(
            model_name='roboadvisorquestionportfoliocomposition',
            name='status',
            field=models.IntegerField(choices=[(1, 'Finished'), (2, 'Abandoned'), (3, 'Started')], default=3),
        ),
        migrations.AddField(
            model_name='roboadvisorquestionportfoliocomposition',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='roboadvisorquestioncompanyanalysis',
            name='asset_knowledge',
            field=models.IntegerField(blank=True, choices=[(1, 'Experto'), (2, 'Profesional'), (3, 'Intermedio'), (4, 'Básico'), (5, 'Nulo')], default=4, null=True),
        ),
        migrations.AlterField(
            model_name='roboadvisorquestioncompanyanalysis',
            name='sector_knowledge',
            field=models.IntegerField(blank=True, choices=[(1, 'Experto'), (2, 'Profesional'), (3, 'Intermedio'), (4, 'Básico'), (5, 'Nulo')], default=4, null=True),
        ),
        migrations.AlterField(
            model_name='roboadvisorquestioninvestorexperience',
            name='age',
            field=models.PositiveIntegerField(blank=True, default=18, null=True),
        ),
        migrations.AlterField(
            model_name='roboadvisorquestioninvestorexperience',
            name='investor_type_self_definition',
            field=models.IntegerField(blank=True, choices=[(1, 'Activo'), (2, 'Intermedio'), (3, 'Pasivo'), (4, 'Especulador')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='roboadvisorquestioninvestorexperience',
            name='objectif',
            field=models.IntegerField(blank=True, choices=[(1, 'Generar ingresos pasivos'), (2, 'Generar un patrimonio'), (3, 'Ahorrar'), (4, 'Ganar dinero rápido')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='roboadvisorquestionportfoliocomposition',
            name='asset_knowledge',
            field=models.IntegerField(blank=True, choices=[(1, 'Experto'), (2, 'Profesional'), (3, 'Intermedio'), (4, 'Básico'), (5, 'Nulo')], default=4, null=True),
        ),
        migrations.AlterField(
            model_name='roboadvisorquestionportfoliocomposition',
            name='sector_knowledge',
            field=models.IntegerField(blank=True, choices=[(1, 'Experto'), (2, 'Profesional'), (3, 'Intermedio'), (4, 'Básico'), (5, 'Nulo')], default=4, null=True),
        ),
    ]
