# Generated by Django 3.2.12 on 2022-04-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roboadvisor', '0010_auto_20220419_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='roboadvisorservice',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
