# Generated by Django 3.2.12 on 2022-04-20 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roboadvisor', '0011_roboadvisorservice_thumbnail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roboadvisorquestioninvestorexperience',
            options={'verbose_name': 'Pregunta: Experiencia como inversor', 'verbose_name_plural': 'Pregunta: Experiencia como inversor'},
        ),
        migrations.RemoveField(
            model_name='roboadvisorquestioncompanyanalysis',
            name='date_finished',
        ),
        migrations.RemoveField(
            model_name='roboadvisorquestioncompanyanalysis',
            name='date_started',
        ),
        migrations.RemoveField(
            model_name='roboadvisorquestioncompanyanalysis',
            name='status',
        ),
        migrations.RemoveField(
            model_name='roboadvisorquestionfinancialsituation',
            name='date_finished',
        ),
        migrations.RemoveField(
            model_name='roboadvisorquestionfinancialsituation',
            name='date_started',
        ),
        migrations.RemoveField(
            model_name='roboadvisorquestionfinancialsituation',
            name='status',
        ),
        migrations.RemoveField(
            model_name='roboadvisorquestioninvestorexperience',
            name='date_finished',
        ),
        migrations.RemoveField(
            model_name='roboadvisorquestioninvestorexperience',
            name='date_started',
        ),
        migrations.RemoveField(
            model_name='roboadvisorquestioninvestorexperience',
            name='status',
        ),
        migrations.RemoveField(
            model_name='roboadvisorquestionportfolioassetsweight',
            name='date_finished',
        ),
        migrations.RemoveField(
            model_name='roboadvisorquestionportfolioassetsweight',
            name='date_started',
        ),
        migrations.RemoveField(
            model_name='roboadvisorquestionportfolioassetsweight',
            name='status',
        ),
        migrations.RemoveField(
            model_name='roboadvisorquestionportfoliocomposition',
            name='date_finished',
        ),
        migrations.RemoveField(
            model_name='roboadvisorquestionportfoliocomposition',
            name='date_started',
        ),
        migrations.RemoveField(
            model_name='roboadvisorquestionportfoliocomposition',
            name='status',
        ),
        migrations.RemoveField(
            model_name='roboadvisorquestionriskaversion',
            name='date_finished',
        ),
        migrations.RemoveField(
            model_name='roboadvisorquestionriskaversion',
            name='date_started',
        ),
        migrations.RemoveField(
            model_name='roboadvisorquestionriskaversion',
            name='status',
        ),
        migrations.RemoveField(
            model_name='roboadvisorquestionstocksportfolio',
            name='date_finished',
        ),
        migrations.RemoveField(
            model_name='roboadvisorquestionstocksportfolio',
            name='date_started',
        ),
        migrations.RemoveField(
            model_name='roboadvisorquestionstocksportfolio',
            name='status',
        ),
        migrations.RemoveField(
            model_name='roboadvisorservicestep',
            name='service_related',
        ),
        migrations.AddField(
            model_name='roboadvisorservicestep',
            name='service_related',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='steps', to='roboadvisor.roboadvisorservice'),
        ),
        migrations.AlterField(
            model_name='roboadvisoruserservicestepactivity',
            name='date_finished',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='roboadvisorquestioninvestorexperience',
            table='roboadvisor_investor_experience',
        ),
    ]
