# Generated by Django 3.2.12 on 2022-04-21 20:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('roboadvisor', '0012_auto_20220420_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roboadvisorquestioninvestorexperience',
            name='years_investing',
        ),
        migrations.AddField(
            model_name='roboadvisorquestioninvestorexperience',
            name='period_investing_exp',
            field=models.PositiveIntegerField(choices=[(0, 'Minutos'), (1, 'Horas'), (2, 'Días'), (3, 'Semanas'), (4, 'Meses'), (5, 'Años')], default=4),
        ),
        migrations.AddField(
            model_name='roboadvisorquestioninvestorexperience',
            name='time_investing_exp',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='roboadvisoruserservicestepactivity',
            name='date_finished',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
