# Generated by Django 3.2.12 on 2022-04-23 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roboadvisor', '0013_auto_20220421_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='roboadvisorservicestep',
            name='slug',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='roboadvisorservicestep',
            name='url',
            field=models.CharField(blank=True, choices=[('stocks-portfolio', 'stocks-portfolio'), ('composition', 'composition'), ('risk-aversion', 'risk-aversion'), ('weights', 'weights'), ('experience', 'experience'), ('financial', 'financial'), ('analysis', 'analysis')], max_length=500, null=True),
        ),
    ]
