# Generated by Django 3.2.12 on 2022-04-26 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roboadvisor', '0015_roboadvisorservice_template_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roboadvisorquestioncompanyanalysis',
            name='service_activity',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='roboadvisor.roboadvisoruserserviceactivity'),
        ),
        migrations.AlterField(
            model_name='roboadvisorquestioncompanyanalysis',
            name='service_step',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='roboadvisor.roboadvisoruserservicestepactivity'),
        ),
        migrations.AlterField(
            model_name='roboadvisorquestionfinancialsituation',
            name='service_activity',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='roboadvisor.roboadvisoruserserviceactivity'),
        ),
        migrations.AlterField(
            model_name='roboadvisorquestionfinancialsituation',
            name='service_step',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='roboadvisor.roboadvisoruserservicestepactivity'),
        ),
        migrations.AlterField(
            model_name='roboadvisorquestioninvestorexperience',
            name='service_activity',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='roboadvisor.roboadvisoruserserviceactivity'),
        ),
        migrations.AlterField(
            model_name='roboadvisorquestioninvestorexperience',
            name='service_step',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='roboadvisor.roboadvisoruserservicestepactivity'),
        ),
        migrations.AlterField(
            model_name='roboadvisorquestionportfolioassetsweight',
            name='service_activity',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='roboadvisor.roboadvisoruserserviceactivity'),
        ),
        migrations.AlterField(
            model_name='roboadvisorquestionportfolioassetsweight',
            name='service_step',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='roboadvisor.roboadvisoruserservicestepactivity'),
        ),
        migrations.AlterField(
            model_name='roboadvisorquestionportfoliocomposition',
            name='service_activity',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='roboadvisor.roboadvisoruserserviceactivity'),
        ),
        migrations.AlterField(
            model_name='roboadvisorquestionportfoliocomposition',
            name='service_step',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='roboadvisor.roboadvisoruserservicestepactivity'),
        ),
        migrations.AlterField(
            model_name='roboadvisorquestionriskaversion',
            name='service_activity',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='roboadvisor.roboadvisoruserserviceactivity'),
        ),
        migrations.AlterField(
            model_name='roboadvisorquestionriskaversion',
            name='service_step',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='roboadvisor.roboadvisoruserservicestepactivity'),
        ),
        migrations.AlterField(
            model_name='roboadvisorquestionstocksportfolio',
            name='service_activity',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='roboadvisor.roboadvisoruserserviceactivity'),
        ),
        migrations.AlterField(
            model_name='roboadvisorquestionstocksportfolio',
            name='service_step',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='roboadvisor.roboadvisoruserservicestepactivity'),
        ),
        migrations.AlterField(
            model_name='roboadvisorservice',
            name='slug',
            field=models.CharField(blank=True, choices=[('company-match', 'company-match'), ('investor-profile', 'investor-profile'), ('optimize-my-portfolio', 'optimize-my-portfolio')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='roboadvisoruserserviceactivity',
            name='status',
            field=models.IntegerField(choices=[(1, 'Finished'), (2, 'Abandoned'), (3, 'Started'), (4, 'Not payed')], default=3),
        ),
        migrations.AlterField(
            model_name='roboadvisoruserservicestepactivity',
            name='status',
            field=models.IntegerField(choices=[(1, 'Finished'), (2, 'Abandoned'), (3, 'Started'), (4, 'Not payed')], default=3),
        ),
    ]
