# Generated by Django 3.2.12 on 2022-04-27 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roboadvisor', '0016_auto_20220426_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investorprofile',
            name='horizon',
            field=models.CharField(blank=True, choices=[('long-term', 'Long Term'), ('medium-term', 'Medium Term'), ('short-term', 'Short Term')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='investorprofile',
            name='investor_type',
            field=models.CharField(blank=True, choices=[('active', 'Activo'), ('intermediate', 'Intermedio'), ('pasive', 'Pasivo'), ('gambler', 'Especulador')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='investorprofile',
            name='risk_profile',
            field=models.TextField(blank=True, choices=[('Las personas con actitudes de riesgo muy agresivas buscan maximizar sus ganancias a largo plazo y están dispuestas a aceptar un riesgo sustancial para lograrlo.A cambio de ese rendimiento esperado más alto, esta actitud de riesgo asume la mayor parte del riesgo de la cartera con potencialmente mucha más volatilidad y un mayor potencial de pérdidas de inversión,así como una gama más amplia de resultados potenciales en el futuro, buenos o malos. Las carteras muy agresivas suelen invertir mucho más en acciones que en bonos o efectivo en relación con los inversores con actitudes menos riesgosas en un esfuerzo por tener el mayor potencial de rendimiento posible.', 'PROFILE VERY AGRESIVE'), ('Las personas con actitudes agresivas frente al riesgo se sienten cómodas asumiendo riesgos y lidiando con la volatilidad del mercado a corto plazo para tener la oportunidad de alcanzar niveles más altos de riqueza en el futuro y cumplir con los objetivos de inversión a largo plazo.Los inversores con actitudes agresivas normalmente utilizarán más acciones en su cartera dado su mejor potencial de rendimiento que los bonos y el efectivo, pero los inversores deben ser conscientes de que el mayor potencial de rendimiento conlleva una mayor volatilidad y un mayor potencial de pérdidas.', 'PROFILE AGRESIVE'), ('Las personas con actitudes conservadoras frente al riesgo se sienten más cómodas con la toma de riesgos en comparación con los inversores muy conservadores, pero aún así prefieren la cautela cuando se trata de invertir. Los inversores con actitudes conservadoras frente al riesgo normalmente utilizarán más bonos o efectivo en su cartera que los inversores con actitudes más riesgosas. Si bien el riesgo de perder dinero debido a un desempeño deficiente del mercado podría reducirse con un enfoque conservador,este tipo de inversión conlleva otros riesgos, como no poder generar suficiente riqueza para cumplir con los objetivos financieros o incluso no poder seguirel ritmo. con inflación para mantener el poder adquisitivo de sus inversiones. Si bien tienen el beneficio de experimentar potencialmente menos altibajos en el mercado,los inversores con actitudes conservadoras de riesgo probablemente necesiten ahorrar más para alcanzar los mismos niveles de riqueza y cumplir los mismos objetivos financieros que aquellos que se sienten cómodos asumiendo más riesgos.', 'PROFILE CONSERVATIVE'), ('Las personas con actitudes de riesgo muy conservadoras buscan inversiones estables con un riesgo mínimo para el capital de sus inversiones.Los inversores con actitudes de riesgo muy conservadoras normalmente utilizarán significativamente más bonos o efectivo en su cartera que los inversores con actitudes más riesgosas.Si bien el riesgo de perder dinero debido a un desempeño deficiente del mercado podría reducirse con un enfoque muy conservador, este tipo de inversión conlleva otros riesgos,como no poder generar suficiente riqueza para cumplir con los objetivos financieros o incluso no poder mantener ritmo con la inflación para mantener el poder adquisitivo de sus inversiones.Si bien tienen el beneficio de experimentar potencialmente menos altibajos en el mercado, los inversores con actitudes de riesgo muy conservadoras probablemente necesiten ahorrar más para alcanzar los mismos niveles de riqueza y cumplir los mismos objetivos financieros que aquellos que se sienten cómodos asumiendo más riesgos.', 'PROFILE VERY CONSERVATIVE'), ('Las personas con actitudes de riesgo moderado asumen cierto riesgo de inversión, pero también desconfían de las desventajas.Los inversores con estos puntos de vista sobre el riesgo se sienten más cómodos con la volatilidad de la inversión hoy en día por el potencial de mejores resultados en el futuro,pero no llegarán a los mismos niveles de toma de riesgo de renta variable que los inversores agresivos o muy agresivos. En relación con los inversores conservadores, puede haber un riesgo reducido de no poder acumularsuficiente riqueza para cumplir los objetivos de jubilación a largo plazo o incluso potencialmente no poder seguir el ritmo de la inflación, pero existe un mayor riesgo de volatilidad de la cartera y de corto plazo. pérdidas de plazo.', 'PROFILE REGULAR')], null=True),
        ),
        migrations.AlterField(
            model_name='roboadvisorquestioncompanyanalysis',
            name='asset_knowledge',
            field=models.CharField(blank=True, choices=[('expert', 'Experto'), ('pro', 'Profesional'), ('intermediate', 'Intermedio'), ('basic', 'Básico'), ('null', 'Nulo')], default=4, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='roboadvisorquestioncompanyanalysis',
            name='horizon_period',
            field=models.CharField(choices=[('minutes', 'Minutos'), ('hours', 'Horas'), ('days', 'Días'), ('weeks', 'Semanas'), ('months', 'Meses'), ('years', 'Años')], default=('months', 'Meses'), max_length=500),
        ),
        migrations.AlterField(
            model_name='roboadvisorquestioncompanyanalysis',
            name='period_time_studied',
            field=models.CharField(choices=[('minutes', 'Minutos'), ('hours', 'Horas'), ('days', 'Días'), ('weeks', 'Semanas'), ('months', 'Meses'), ('years', 'Años')], default=('months', 'Meses'), max_length=500),
        ),
        migrations.AlterField(
            model_name='roboadvisorquestioncompanyanalysis',
            name='result',
            field=models.CharField(blank=True, choices=[('Buy', 'Comprar'), ('Sell', 'Vender'), ('Hold', 'Mantener'), ('Error', 'Mantener')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='roboadvisorquestioncompanyanalysis',
            name='sector_knowledge',
            field=models.CharField(blank=True, choices=[('expert', 'Experto'), ('pro', 'Profesional'), ('intermediate', 'Intermedio'), ('basic', 'Básico'), ('null', 'Nulo')], default=4, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='roboadvisorquestioninvestorexperience',
            name='investor_type_self_definition',
            field=models.CharField(blank=True, choices=[('active', 'Activo'), ('intermediate', 'Intermedio'), ('pasive', 'Pasivo'), ('gambler', 'Especulador')], default=('intermediate', 'Intermedio'), max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='roboadvisorquestioninvestorexperience',
            name='objectif',
            field=models.CharField(blank=True, choices=[(1, 'Generar ingresos pasivos'), (2, 'Generar un patrimonio'), (3, 'Ahorrar'), (4, 'Ganar dinero rápido')], default=1, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='roboadvisorquestioninvestorexperience',
            name='period_investing_exp',
            field=models.CharField(choices=[('minutes', 'Minutos'), ('hours', 'Horas'), ('days', 'Días'), ('weeks', 'Semanas'), ('months', 'Meses'), ('years', 'Años')], default=('months', 'Meses'), max_length=500),
        ),
        migrations.AlterField(
            model_name='roboadvisorquestionportfoliocomposition',
            name='asset_knowledge',
            field=models.CharField(blank=True, choices=[('expert', 'Experto'), ('pro', 'Profesional'), ('intermediate', 'Intermedio'), ('basic', 'Básico'), ('null', 'Nulo')], default=4, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='roboadvisorquestionportfoliocomposition',
            name='horizon_period',
            field=models.CharField(choices=[('minutes', 'Minutos'), ('hours', 'Horas'), ('days', 'Días'), ('weeks', 'Semanas'), ('months', 'Meses'), ('years', 'Años')], default=('months', 'Meses'), max_length=500),
        ),
        migrations.AlterField(
            model_name='roboadvisorquestionportfoliocomposition',
            name='period_time_studied',
            field=models.CharField(choices=[('minutes', 'Minutos'), ('hours', 'Horas'), ('days', 'Días'), ('weeks', 'Semanas'), ('months', 'Meses'), ('years', 'Años')], default=('months', 'Meses'), max_length=500),
        ),
        migrations.AlterField(
            model_name='roboadvisorquestionportfoliocomposition',
            name='sector_knowledge',
            field=models.CharField(blank=True, choices=[('expert', 'Experto'), ('pro', 'Profesional'), ('intermediate', 'Intermedio'), ('basic', 'Básico'), ('null', 'Nulo')], default=4, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='roboadvisorquestionriskaversion',
            name='horizon_period',
            field=models.CharField(choices=[('minutes', 'Minutos'), ('hours', 'Horas'), ('days', 'Días'), ('weeks', 'Semanas'), ('months', 'Meses'), ('years', 'Años')], default=('months', 'Meses'), max_length=500),
        ),
        migrations.AlterField(
            model_name='roboadvisoruserserviceactivity',
            name='status',
            field=models.CharField(choices=[('finished', 'Finished'), ('abandoned', 'Abandoned'), ('started', 'Started'), ('not-payed', 'Not payed')], default=('started', 'Started'), max_length=500),
        ),
        migrations.AlterField(
            model_name='roboadvisoruserservicestepactivity',
            name='status',
            field=models.CharField(choices=[('finished', 'Finished'), ('abandoned', 'Abandoned'), ('started', 'Started'), ('not-payed', 'Not payed')], default=('started', 'Started'), max_length=500),
        ),
        migrations.AlterField(
            model_name='temporaryinvestorprofile',
            name='horizon',
            field=models.CharField(blank=True, choices=[('long-term', 'Long Term'), ('medium-term', 'Medium Term'), ('short-term', 'Short Term')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='temporaryinvestorprofile',
            name='investor_type',
            field=models.CharField(blank=True, choices=[('active', 'Activo'), ('intermediate', 'Intermedio'), ('pasive', 'Pasivo'), ('gambler', 'Especulador')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='temporaryinvestorprofile',
            name='risk_profile',
            field=models.TextField(blank=True, choices=[('Las personas con actitudes de riesgo muy agresivas buscan maximizar sus ganancias a largo plazo y están dispuestas a aceptar un riesgo sustancial para lograrlo.A cambio de ese rendimiento esperado más alto, esta actitud de riesgo asume la mayor parte del riesgo de la cartera con potencialmente mucha más volatilidad y un mayor potencial de pérdidas de inversión,así como una gama más amplia de resultados potenciales en el futuro, buenos o malos. Las carteras muy agresivas suelen invertir mucho más en acciones que en bonos o efectivo en relación con los inversores con actitudes menos riesgosas en un esfuerzo por tener el mayor potencial de rendimiento posible.', 'PROFILE VERY AGRESIVE'), ('Las personas con actitudes agresivas frente al riesgo se sienten cómodas asumiendo riesgos y lidiando con la volatilidad del mercado a corto plazo para tener la oportunidad de alcanzar niveles más altos de riqueza en el futuro y cumplir con los objetivos de inversión a largo plazo.Los inversores con actitudes agresivas normalmente utilizarán más acciones en su cartera dado su mejor potencial de rendimiento que los bonos y el efectivo, pero los inversores deben ser conscientes de que el mayor potencial de rendimiento conlleva una mayor volatilidad y un mayor potencial de pérdidas.', 'PROFILE AGRESIVE'), ('Las personas con actitudes conservadoras frente al riesgo se sienten más cómodas con la toma de riesgos en comparación con los inversores muy conservadores, pero aún así prefieren la cautela cuando se trata de invertir. Los inversores con actitudes conservadoras frente al riesgo normalmente utilizarán más bonos o efectivo en su cartera que los inversores con actitudes más riesgosas. Si bien el riesgo de perder dinero debido a un desempeño deficiente del mercado podría reducirse con un enfoque conservador,este tipo de inversión conlleva otros riesgos, como no poder generar suficiente riqueza para cumplir con los objetivos financieros o incluso no poder seguirel ritmo. con inflación para mantener el poder adquisitivo de sus inversiones. Si bien tienen el beneficio de experimentar potencialmente menos altibajos en el mercado,los inversores con actitudes conservadoras de riesgo probablemente necesiten ahorrar más para alcanzar los mismos niveles de riqueza y cumplir los mismos objetivos financieros que aquellos que se sienten cómodos asumiendo más riesgos.', 'PROFILE CONSERVATIVE'), ('Las personas con actitudes de riesgo muy conservadoras buscan inversiones estables con un riesgo mínimo para el capital de sus inversiones.Los inversores con actitudes de riesgo muy conservadoras normalmente utilizarán significativamente más bonos o efectivo en su cartera que los inversores con actitudes más riesgosas.Si bien el riesgo de perder dinero debido a un desempeño deficiente del mercado podría reducirse con un enfoque muy conservador, este tipo de inversión conlleva otros riesgos,como no poder generar suficiente riqueza para cumplir con los objetivos financieros o incluso no poder mantener ritmo con la inflación para mantener el poder adquisitivo de sus inversiones.Si bien tienen el beneficio de experimentar potencialmente menos altibajos en el mercado, los inversores con actitudes de riesgo muy conservadoras probablemente necesiten ahorrar más para alcanzar los mismos niveles de riqueza y cumplir los mismos objetivos financieros que aquellos que se sienten cómodos asumiendo más riesgos.', 'PROFILE VERY CONSERVATIVE'), ('Las personas con actitudes de riesgo moderado asumen cierto riesgo de inversión, pero también desconfían de las desventajas.Los inversores con estos puntos de vista sobre el riesgo se sienten más cómodos con la volatilidad de la inversión hoy en día por el potencial de mejores resultados en el futuro,pero no llegarán a los mismos niveles de toma de riesgo de renta variable que los inversores agresivos o muy agresivos. En relación con los inversores conservadores, puede haber un riesgo reducido de no poder acumularsuficiente riqueza para cumplir los objetivos de jubilación a largo plazo o incluso potencialmente no poder seguir el ritmo de la inflación, pero existe un mayor riesgo de volatilidad de la cartera y de corto plazo. pérdidas de plazo.', 'PROFILE REGULAR')], null=True),
        ),
    ]
