# Generated by Django 3.2.12 on 2022-05-21 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('general', '0003_auto_20220415_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_blog_post', 'Nuevo escrito'), ('new_comment', 'Nuevo comentario'), ('new_vote', 'Nuevo voto'), ('new_follower', 'Nuevo seguidor'), ('new_question', 'Nueva pregunta'), ('new_answer', 'Nueva respuesta'), ('answer_accepted', 'Respuesta acceptada'), ('new_obs_company', 'Nuevo análisis'), ('new_news_company', 'Nuevas noticias para tu empresa')], max_length=250, null=True),
        ),
        migrations.DeleteModel(
            name='NotificationsType',
        ),
    ]
