# Generated by Django 3.2.12 on 2022-06-05 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcomplementary',
            old_name='secondary_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='productcomplementary',
            old_name='secondary_slug',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='productcomplementary',
            old_name='stripe_price_id',
            new_name='stripe_id',
        ),
        migrations.RenameField(
            model_name='productcomplementary',
            old_name='secondary_title',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=300),
        ),
        migrations.CreateModel(
            name='ProductComplementaryPaymentLunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(blank=True, max_length=500, null=True)),
                ('stripe_id', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('product_complementary', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_links', to='business.productcomplementary')),
            ],
            options={
                'verbose_name': 'Product complementary payment link',
                'verbose_name_plural': 'Products complementary payment link',
                'db_table': 'business_products_complementary_payment_link',
            },
        ),
    ]
