# Generated by Django 3.2.12 on 2022-06-05 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductComplementaryPaymentLunk',
            new_name='ProductComplementaryPaymentLink',
        ),
    ]
