# Generated by Django 3.2.12 on 2022-06-13 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcomplementary',
            name='product_result',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='productcomplementary',
            name='purchase_result',
            field=models.CharField(blank=True, choices=[('add_credits', 'add_credits'), ('share_excel', 'share_excel'), ('ilimited_credits', 'ilimited_credits'), ('random_prize', 'random_prize'), ('random_credits', 'random_credits')], max_length=300),
        ),
        migrations.AddField(
            model_name='productcomplementarypaymentlink',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='productcomplementarypaymentlink',
            name='for_website',
            field=models.BooleanField(default=False),
        ),
    ]
