# Generated by Django 3.2.12 on 2022-06-06 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0007_auto_20220605_2147'),
        ('business', '0002_rename_productcomplementarypaymentlunk_productcomplementarypaymentlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcomplementary',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='productcomplementary',
            name='video',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='productcomplementarypaymentlink',
            name='for_website',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productcomplementarypaymentlink',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotion_link_payment', to='seo.promotion'),
        ),
        migrations.AddField(
            model_name='productdiscount',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotion_discount', to='seo.promotion'),
        ),
        migrations.AlterField(
            model_name='productcomplementary',
            name='extras',
            field=models.JSONField(default={'include': [{'icon': "<i class='fas fa-infinity'></i>", 'text': 'Acceso de por vida'}, {'icon': "<i class='fas fa-file-archive'></i>", 'text': 'Actualizaciones constantes'}, {'icon': "<i class='fas fa-book'></i>", 'text': 'Ebook de regalo'}], 'title': '¿Qué incluye?'}),
        ),
    ]
