# Generated by Django 3.2.12 on 2022-06-04 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_auto_20220604_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcomplementary',
            name='secondary_slug',
            field=models.SlugField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='productcomplementary',
            name='secondary_title',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
