# Generated by Django 3.2.12 on 2022-06-06 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_auto_20220606_2329'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeWebhookResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_response', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='business.customer')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='business.product')),
                ('product_complementary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='business.productcomplementary')),
            ],
            options={
                'verbose_name': 'Stripe webhook response',
                'verbose_name_plural': 'Stripe webhook responses',
                'db_table': 'business_stripe_webhook_responses',
            },
        ),
    ]
