# Generated by Django 3.2.14 on 2022-07-25 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_promotion_promotioncampaign'),
        ('business', '0003_auto_20220620_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomplementarypaymentlink',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotion_link_payment', to='web.promotion'),
        ),
        migrations.AlterField(
            model_name='productdiscount',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotion_discount', to='web.promotion'),
        ),
    ]
