# Generated by Django 3.2.12 on 2022-06-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_auto_20220604_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionhistorial',
            name='stripe_response',
            field=models.JSONField(default=dict),
        ),
    ]
