# Generated by Django 3.2.12 on 2022-06-04 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_transactionhistorial_stripe_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productcomplementary',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='transactionhistorial',
            name='stripe_response',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
