# Generated by Django 3.2.12 on 2022-06-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_auto_20220604_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcomplementary',
            name='subscription_interval',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='productcomplementary',
            name='subscription_period',
            field=models.CharField(blank=True, choices=[('day', 'Daily'), ('week', 'Weekly'), ('month', 'Montly'), ('year', 'Yearly')], max_length=300),
        ),
    ]
