# Generated by Django 3.2.12 on 2022-06-04 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_auto_20220604_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdiscount',
            name='is_percentage',
            field=models.BooleanField(default=True),
        ),
    ]
