# Generated by Django 3.2.12 on 2022-06-04 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_productdiscount_is_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdiscount',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
