# Generated by Django 3.2.12 on 2022-06-04 23:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_productdiscount_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcomplementary',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productcomplementary',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
