# Generated by Django 3.2.12 on 2022-03-19 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0002_auto_20220306_1943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userscreenermediumprediction',
            old_name='neutral_per',
            new_name='neutral_fcf_margin',
        ),
        migrations.RenameField(
            model_name='userscreenermediumprediction',
            old_name='optimistic_per',
            new_name='optimistic_fcf_margin',
        ),
        migrations.RenameField(
            model_name='userscreenermediumprediction',
            old_name='pesimistic_per',
            new_name='pesimistic_fcf_margin',
        ),
    ]
