# Generated by Django 3.2.12 on 2022-05-22 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_auto_20220415_0001'),
        ('screener', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YahooScreener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('slug', models.SlugField(max_length=500)),
                ('description', models.TextField()),
                ('json_info', models.JSONField(default=dict)),
                ('yq_name', models.CharField(max_length=500)),
                ('asset_class_related', models.CharField(choices=[('etf', 'ETF'), ('stock', 'Stock'), ('crypto', 'Crypto'), ('mutual_fund', 'Mutual Fund'), ('reit', 'REIT')], max_length=25)),
                ('show', models.BooleanField(default=True)),
                ('categories', models.ManyToManyField(blank=True, to='general.Category')),
                ('tags', models.ManyToManyField(blank=True, to='general.Tag')),
            ],
            options={
                'verbose_name': 'Yahoo screener',
                'db_table': 'screener_yahoo_screeners',
            },
        ),
    ]
