# Generated by Django 3.2.12 on 2022-07-04 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0011_company_checkings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('screener', '0003_yahooscreener'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInformationBought',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empresas.company')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Acción comprada',
                'verbose_name_plural': 'Acciones compradas',
                'db_table': 'favorites_stocks_boughts',
            },
        ),
    ]
