SOCIAL_MEDIAS = (
    ('facebook', 'Facebook'), 
    ('twitter', 'Twitter'), 
    ('reddit', 'Reddit'), 
    ('whatsapp', 'Whatsapp'), 
    ('linkedin', 'Linkedin'), 
    ('pinterest', 'Pinterest'), 
    ('tumblr', 'Tumblr'),
    ('instagram', 'Instagram')
)

FOR_MODEL = (
    (1, 'Question'),
    (2, 'News'),
    (3, 'Term'),
    (4, 'Blog'),
    (5, 'Company')
)

POST_TYPE = (
    (1, 'Video'), 
    (2, 'Image'), 
    (3, 'Text'),
    (4, 'Repost'), 
    (5, 'Text and video'), 
    (6, 'Text and image'), 
    (7, 'Shorts'))


IG_HASHTAGS = ["valueinvestor", "valueinvesting", "invertirenvenezuela", "invertirencolombia", "invertirenespaña", "invertirmejor®", 
 "ingresospasivos", "inversionista", "inversionesinteligente", "bolsas", "inversión"]

FB_HASHTAGS = ["valueinvesting", "InvertirMejorQueAhorrar", "invertientufuturo", "inversionchallenge", "inversionista", "inversionesinteligentes", 
 "bolsa", "invertirenbolsa", "invertirmejor", 
 "inversiones", "invertir", "bolsadevalores", "invertirbien", "inversion", "invertironline"]

ICONS = ['😀',
 '😃',
 '😄',
 '😁',
 '😆',
 '😅',
 '😂',
 '🤣',
 '\U0001f972',
 '☺️',
 '😊',
 '😇',
 '🙂',
 '🙃',
 '😉',
 '😌',
 '😍',
 '🥰',
 '😘',
 '😗',
 '😙',
 '😚',
 '😋',
 '😛',
 '😝',
 '😜',
 '🤪',
 '🤨',
 '🧐',
 '🤓',
 '😎',
 '\U0001f978',
 '🤩',
 '🥳',
 '😏',
 '😒',
 '😞',
 '😔',
 '😟',
 '😕',
 '🙁',
 '☹️',
 '😣',
 '😖',
 '😫',
 '😩',
 '🥺',
 '😢',
 '😭',
 '😤',
 '😠',
 '😡',
 '🤬',
 '🤯',
 '😳',
 '🥵',
 '🥶',
 '😱',
 '😨',
 '😰',
 '😥',
 '😓',
 '🤗',
 '🤔',
 '🤭',
 '🤫',
 '🤥',
 '😶',
 '😐',
 '😑',
 '💸',
 '💵',
 '💴',
 '💶',
 '💷',
 '\U0001fa99',
 '💰',
 '💳',
 '💎',
 '⚖️',
 '\U0001fa9c',
 '🧰',
 '\U0001fa9b']

TWITTER_HASHTAGS = ['invertir', 'inversiones', 'valueinvesting', 'invertirenvalor', 'inversionesinteligente',
    'bolsa', 'invertirenbolsa', 'inversorinteligente']