# Generated by Django 3.2.12 on 2022-03-08 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['-name'], 'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
    ]
