# Generated by Django 3.2.12 on 2022-03-14 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_alter_company_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancesheet',
            name='year',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cashflowstatement',
            name='year',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='company',
            name='date_updated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='last_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='updated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companygrowth',
            name='year',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='companystockprice',
            name='year',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='eficiencyratio',
            name='year',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='enterprisevalueratio',
            name='year',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='freecashflowratio',
            name='year',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='incomestatement',
            name='year',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='liquidityratio',
            name='year',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='marginratio',
            name='year',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='nongaap',
            name='year',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='operationriskratio',
            name='year',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='persharevalue',
            name='year',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pricetoratio',
            name='year',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='rentabilityratio',
            name='year',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='date',
            field=models.IntegerField(default=0),
        ),
    ]
