# Generated by Django 3.2.12 on 2022-03-16 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_auto_20220314_1617'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='balancesheet',
            options={'get_latest_by': 'date', 'ordering': ['-date'], 'verbose_name': 'Balance Sheet', 'verbose_name_plural': 'Balance Sheets'},
        ),
        migrations.AlterModelOptions(
            name='cashflowstatement',
            options={'get_latest_by': 'date', 'ordering': ['-date'], 'verbose_name': 'Cash flow Statement', 'verbose_name_plural': 'Cash flow Statements'},
        ),
        migrations.AlterModelOptions(
            name='companygrowth',
            options={'get_latest_by': 'date', 'ordering': ['-date'], 'verbose_name': 'Company growth', 'verbose_name_plural': 'Companies growth'},
        ),
        migrations.AlterModelOptions(
            name='companystockprice',
            options={'get_latest_by': 'date', 'ordering': ['-date'], 'verbose_name': 'Company stock price', 'verbose_name_plural': 'Company stock prices'},
        ),
        migrations.AlterModelOptions(
            name='eficiencyratio',
            options={'get_latest_by': 'date', 'ordering': ['-date'], 'verbose_name': 'Efficiency Ratio', 'verbose_name_plural': 'Efficiency Ratios'},
        ),
        migrations.AlterModelOptions(
            name='enterprisevalueratio',
            options={'get_latest_by': 'date', 'ordering': ['-date'], 'verbose_name': 'Enterprise Value', 'verbose_name_plural': 'Enterprise Values'},
        ),
        migrations.AlterModelOptions(
            name='freecashflowratio',
            options={'get_latest_by': 'date', 'ordering': ['-date'], 'verbose_name': 'Free cash flow Ratio', 'verbose_name_plural': 'Free cash flow Ratios'},
        ),
        migrations.AlterModelOptions(
            name='incomestatement',
            options={'get_latest_by': 'date', 'ordering': ['-date'], 'verbose_name': 'Income Statement', 'verbose_name_plural': 'Income Statements'},
        ),
        migrations.AlterModelOptions(
            name='liquidityratio',
            options={'get_latest_by': 'date', 'ordering': ['-date'], 'verbose_name': 'Liquidity Ratio', 'verbose_name_plural': 'Liquidity Ratios'},
        ),
        migrations.AlterModelOptions(
            name='marginratio',
            options={'get_latest_by': 'date', 'ordering': ['-date'], 'verbose_name': 'Margin Ratio', 'verbose_name_plural': 'Margin Ratios'},
        ),
        migrations.AlterModelOptions(
            name='nongaap',
            options={'get_latest_by': 'date', 'ordering': ['-date'], 'verbose_name': 'Non GAAP figure', 'verbose_name_plural': 'Non GAAP figures'},
        ),
        migrations.AlterModelOptions(
            name='operationriskratio',
            options={'get_latest_by': 'date', 'ordering': ['-date'], 'verbose_name': 'Operation Risk Ratio', 'verbose_name_plural': 'Operation Risk Ratios'},
        ),
        migrations.AlterModelOptions(
            name='persharevalue',
            options={'get_latest_by': 'date', 'ordering': ['-date'], 'verbose_name': 'Per share', 'verbose_name_plural': 'Per shares'},
        ),
        migrations.AlterModelOptions(
            name='pricetoratio',
            options={'get_latest_by': 'date', 'ordering': ['-date'], 'verbose_name': 'Price to Ratio', 'verbose_name_plural': 'Price to Ratios'},
        ),
        migrations.AlterModelOptions(
            name='rentabilityratio',
            options={'get_latest_by': 'date', 'ordering': ['-date'], 'verbose_name': 'Rentability Ratio', 'verbose_name_plural': 'Rentability Ratios'},
        ),
    ]
