# Generated by Django 3.2.12 on 2022-05-13 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0004_alter_company_ticker'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['ticker'], 'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AddField(
            model_name='company',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='has_error',
            field=models.BooleanField(default=False),
        ),
    ]
