# Generated by Django 3.2.12 on 2022-05-29 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0005_auto_20220513_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='remote_image_cloudinary',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='company',
            name='remote_image_imagekit',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
