# Generated by Django 3.2.12 on 2022-05-29 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0006_auto_20220529_1246'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionalOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Institutional Organization',
                'verbose_name_plural': 'Institutional Organizations',
                'db_table': 'assets_institutional_organizations',
            },
        ),
        migrations.CreateModel(
            name='TopInstitutionalOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField(default=0)),
                ('year', models.DateField(blank=True, null=True)),
                ('percentage_held', models.FloatField(blank=True, default=0, null=True)),
                ('position', models.FloatField(blank=True, default=0, null=True)),
                ('value', models.FloatField(blank=True, default=0, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='top_institutional_ownership', to='empresas.company')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='institution', to='empresas.institutionalorganization')),
            ],
            options={
                'verbose_name': 'Top institutional owners',
                'verbose_name_plural': 'Top institutional owners',
                'db_table': 'assets_top_institutional_ownership',
                'ordering': ['-date'],
                'get_latest_by': 'date',
            },
        ),
    ]
