# Generated by Django 3.2.12 on 2022-06-15 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0007_institutionalorganization_topinstitutionalownership'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyUpdateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('where', models.CharField(max_length=250)),
                ('had_error', models.BooleanField(default=False)),
                ('error_message', models.TextField(default='')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_log_historial', to='empresas.company')),
            ],
            options={
                'verbose_name': 'Company updates logs',
                'verbose_name_plural': 'Company updates logs',
                'db_table': 'assets_companies_updates_logs',
                'ordering': ['-date'],
                'get_latest_by': 'date',
            },
        ),
    ]
