# Generated by Django 3.2.12 on 2022-06-20 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0008_companyupdatelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyupdatelog',
            name='error_message',
            field=models.TextField(default='', null=True),
        ),
    ]
