# Generated by Django 3.2.12 on 2022-06-25 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0009_alter_companyupdatelog_error_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companystockprice',
            options={'get_latest_by': 'date', 'ordering': ['-date'], 'verbose_name': 'Stock price', 'verbose_name_plural': 'Stock prices'},
        ),
        migrations.AlterModelOptions(
            name='companyupdatelog',
            options={'get_latest_by': 'date', 'ordering': ['-date'], 'verbose_name': 'Logs', 'verbose_name_plural': 'Logs'},
        ),
    ]
