# Generated by Django 3.2.12 on 2022-07-01 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0010_auto_20220625_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='checkings',
            field=models.JSONField(default={'has_institutionals': {'state': 'no', 'time': ''}}),
        ),
    ]
