# Generated by Django 3.2.12 on 2022-05-02 20:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cartera', '0004_auto_20220502_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialobjectif',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialobjectif',
            name='is_rule',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='financialobjectif',
            name='requirement',
            field=models.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='financialobjectif',
            name='rule_ends',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='financialobjectif',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financialobjectif',
            name='name',
            field=models.CharField(max_length=1000, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='patrimonio',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_patrimoine', to=settings.AUTH_USER_MODEL),
        ),
    ]
