# Generated by Django 3.2.12 on 2022-05-03 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_auto_20220415_0001'),
        ('cartera', '0005_auto_20220502_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashflowmovementcategory',
            name='user',
        ),
        migrations.AlterField(
            model_name='financialobjectif',
            name='requirement',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='patrimonio',
            name='default_currency',
            field=models.ForeignKey(blank=True, default='USD', null=True, on_delete=django.db.models.deletion.SET_NULL, to='general.currency'),
        ),
    ]
