# Generated by Django 3.2.12 on 2022-05-06 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0006_auto_20220503_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positionmovement',
            name='asset_related',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='cartera.asset'),
        ),
    ]
