# Generated by Django 3.2.12 on 2022-07-01 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0008_alter_patrimonio_default_currency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='positionmovement',
            options={'ordering': ['-date'], 'verbose_name': 'Position movement', 'verbose_name_plural': 'Position movements'},
        ),
    ]
