# Generated by Django 3.2.12 on 2022-03-06 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined']},
        ),
        migrations.AlterField(
            model_name='profile',
            name='ref_code',
            field=models.CharField(blank=True, max_length=1000, unique=True),
        ),
    ]
