# Generated by Django 3.2.12 on 2022-05-26 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220423_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metaprofile',
            name='ip',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
