# Generated by Django 3.2.12 on 2022-05-21 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220423_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='answer_accepted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='new_answer',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='new_blog_post',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='new_comment',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='new_follower',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='new_news_company',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='new_obs_company',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='new_question',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='new_vote',
            field=models.BooleanField(default=True),
        ),
    ]
