# Generated by Django 3.2.12 on 2022-07-04 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_creditusagehistorial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditusagehistorial',
            name='move_source',
            field=models.CharField(choices=[('excel_usage', 'EXCEL USAGE'), ('excel_gift', 'EXCEL GIFT'), ('bought_credits', 'BOUGHT Credits'), ('screener_usage', 'SCREENER USAGE'), ('prize', 'PRIZE'), ('api_usage', 'API USAGE'), ('question_upvote', 'QUESTION UPVOTE'), ('answer_upvote', 'ANSWER UPVOTE'), ('answer_approved', 'ANSWER APPROVED'), ('term_correction', 'TERM CORRECTION'), ('bought_product', 'Bought Product'), ('bought_company_info', 'Bought Company Info'), ('roboadvisor_usage', 'Roboadvisor Usage')], max_length=100),
        ),
    ]
