# Generated by Django 3.2.12 on 2022-05-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaulttilte',
            name='for_model',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Question'), (2, 'News'), (3, 'Term'), (4, 'Blog'), (5, 'Company')], default=0),
        ),
        migrations.AlterField(
            model_name='blogsharedhistorial',
            name='post_type',
            field=models.PositiveIntegerField(choices=[(1, 'Video'), (2, 'Image'), (3, 'Text'), (4, 'Repost'), (5, 'Text and video'), (6, 'Text and image'), (7, 'Shorts')]),
        ),
        migrations.AlterField(
            model_name='companysharedhistorial',
            name='post_type',
            field=models.PositiveIntegerField(choices=[(1, 'Video'), (2, 'Image'), (3, 'Text'), (4, 'Repost'), (5, 'Text and video'), (6, 'Text and image'), (7, 'Shorts')]),
        ),
        migrations.AlterField(
            model_name='defaulttilte',
            name='title',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='hashtag',
            name='name',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='newssharedhistorial',
            name='post_type',
            field=models.PositiveIntegerField(choices=[(1, 'Video'), (2, 'Image'), (3, 'Text'), (4, 'Repost'), (5, 'Text and video'), (6, 'Text and image'), (7, 'Shorts')]),
        ),
        migrations.AlterField(
            model_name='profilesharedhistorial',
            name='post_type',
            field=models.PositiveIntegerField(choices=[(1, 'Video'), (2, 'Image'), (3, 'Text'), (4, 'Repost'), (5, 'Text and video'), (6, 'Text and image'), (7, 'Shorts')]),
        ),
        migrations.AlterField(
            model_name='questionsharedhistorial',
            name='post_type',
            field=models.PositiveIntegerField(choices=[(1, 'Video'), (2, 'Image'), (3, 'Text'), (4, 'Repost'), (5, 'Text and video'), (6, 'Text and image'), (7, 'Shorts')]),
        ),
        migrations.AlterField(
            model_name='termsharedhistorial',
            name='post_type',
            field=models.PositiveIntegerField(choices=[(1, 'Video'), (2, 'Image'), (3, 'Text'), (4, 'Repost'), (5, 'Text and video'), (6, 'Text and image'), (7, 'Shorts')]),
        ),
    ]
