# Generated by Django 3.2.12 on 2022-05-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedias', '0002_auto_20220506_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogsharedhistorial',
            name='post_type',
            field=models.PositiveIntegerField(choices=[(1, 'Video'), (2, 'Image'), (3, 'Text'), (4, 'Repost'), (5, 'Text and video'), (6, 'Text and image'), (7, 'Shorts'), (8, 'Thread')]),
        ),
        migrations.AlterField(
            model_name='companysharedhistorial',
            name='post_type',
            field=models.PositiveIntegerField(choices=[(1, 'Video'), (2, 'Image'), (3, 'Text'), (4, 'Repost'), (5, 'Text and video'), (6, 'Text and image'), (7, 'Shorts'), (8, 'Thread')]),
        ),
        migrations.AlterField(
            model_name='newssharedhistorial',
            name='post_type',
            field=models.PositiveIntegerField(choices=[(1, 'Video'), (2, 'Image'), (3, 'Text'), (4, 'Repost'), (5, 'Text and video'), (6, 'Text and image'), (7, 'Shorts'), (8, 'Thread')]),
        ),
        migrations.AlterField(
            model_name='profilesharedhistorial',
            name='post_type',
            field=models.PositiveIntegerField(choices=[(1, 'Video'), (2, 'Image'), (3, 'Text'), (4, 'Repost'), (5, 'Text and video'), (6, 'Text and image'), (7, 'Shorts'), (8, 'Thread')]),
        ),
        migrations.AlterField(
            model_name='questionsharedhistorial',
            name='post_type',
            field=models.PositiveIntegerField(choices=[(1, 'Video'), (2, 'Image'), (3, 'Text'), (4, 'Repost'), (5, 'Text and video'), (6, 'Text and image'), (7, 'Shorts'), (8, 'Thread')]),
        ),
        migrations.AlterField(
            model_name='termsharedhistorial',
            name='post_type',
            field=models.PositiveIntegerField(choices=[(1, 'Video'), (2, 'Image'), (3, 'Text'), (4, 'Repost'), (5, 'Text and video'), (6, 'Text and image'), (7, 'Shorts'), (8, 'Thread')]),
        ),
    ]
