# Generated by Django 3.2.12 on 2022-03-28 15:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetaParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, max_length=99999, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('meta_img', models.CharField(blank=True, max_length=99999, null=True)),
                ('meta_url', models.CharField(blank=True, max_length=99999, null=True)),
                ('meta_keywords', models.TextField()),
                ('published_time', models.DateTimeField(auto_now=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('views', models.PositiveBigIntegerField(default=0)),
                ('schema_org', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Meta information',
                'db_table': 'meta_information',
            },
        ),
        migrations.CreateModel(
            name='MetaParametersHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_use', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Historial meta información',
                'db_table': 'meta_information_historial',
            },
        ),
        migrations.CreateModel(
            name='UsersJourney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('current_path', models.CharField(blank=True, max_length=20000, null=True)),
                ('comes_from', models.CharField(blank=True, max_length=20000, null=True)),
            ],
            options={
                'verbose_name': 'Historial visitas usuarios',
                'db_table': 'visits_historial_users',
            },
        ),
        migrations.CreateModel(
            name='Visiteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=10000, null=True)),
                ('session_id', models.CharField(blank=True, max_length=10000, null=True)),
                ('HTTP_USER_AGENT', models.CharField(blank=True, max_length=10000, null=True)),
                ('country_code', models.CharField(blank=True, max_length=10000, null=True)),
                ('country_name', models.CharField(blank=True, max_length=10000, null=True)),
                ('dma_code', models.CharField(blank=True, max_length=10000, null=True)),
                ('is_in_european_union', models.BooleanField(blank=True, null=True)),
                ('latitude', models.CharField(blank=True, max_length=10000, null=True)),
                ('longitude', models.CharField(blank=True, max_length=10000, null=True)),
                ('city', models.CharField(blank=True, max_length=10000, null=True)),
                ('region', models.CharField(blank=True, max_length=10000, null=True)),
                ('time_zone', models.CharField(blank=True, max_length=10000, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=10000, null=True)),
                ('continent_code', models.CharField(blank=True, max_length=10000, null=True)),
                ('continent_name', models.CharField(blank=True, max_length=10000, null=True)),
                ('first_visit_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Visiteur',
                'db_table': 'visiteurs',
            },
        ),
        migrations.CreateModel(
            name='VisiteurJourney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('current_path', models.CharField(blank=True, max_length=20000, null=True)),
                ('comes_from', models.CharField(blank=True, max_length=20000, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seo.visiteur')),
            ],
            options={
                'verbose_name': 'Historial visitas anónimos',
                'db_table': 'visits_historial_visiteurs',
            },
        ),
    ]
