# Generated by Django 3.2.12 on 2022-03-07 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visiteur',
            old_name='visit_date',
            new_name='first_visit_date',
        ),
        migrations.AddField(
            model_name='metaparameters',
            name='schema_org',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
