# Generated by Django 3.2.12 on 2022-03-09 00:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seo', '0002_auto_20220307_0312'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisiteurJourney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('current_path', models.CharField(blank=True, max_length=20000, null=True)),
                ('comes_from', models.CharField(blank=True, max_length=20000, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seo.visiteur')),
            ],
            options={
                'verbose_name': 'Historial visitas anónimos',
                'db_table': 'visits_historial_visiteurs',
            },
        ),
        migrations.CreateModel(
            name='UsersJourney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('current_path', models.CharField(blank=True, max_length=20000, null=True)),
                ('comes_from', models.CharField(blank=True, max_length=20000, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial visitas usuarios',
                'db_table': 'visits_historial_users',
            },
        ),
    ]
