# Generated by Django 3.2.12 on 2022-05-26 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0003_promotion_promotioncampaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metaparameters',
            name='meta_img',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='metaparameters',
            name='meta_title',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='metaparameters',
            name='meta_url',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='usersjourney',
            name='comes_from',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='usersjourney',
            name='current_path',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='visiteur',
            name='ip',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='visiteurjourney',
            name='comes_from',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='visiteurjourney',
            name='current_path',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
