# Generated by Django 3.2.12 on 2022-05-29 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seo', '0004_auto_20220527_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotioncampaign',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promotioncampaign',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='VisiteurUserRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('visiteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='seo.visiteur')),
            ],
            options={
                'verbose_name': 'Visiteur and user relation',
                'db_table': 'visiteur_user_relateds',
            },
        ),
    ]
