# Generated by Django 3.2.12 on 2022-06-03 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0007_institutionalorganization_topinstitutionalownership'),
        ('preguntas_respuestas', '0006_auto_20220603_1924'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('escritos', '0007_auto_20220603_1924'),
        ('public_blog', '0006_auto_20220603_1924'),
        ('seo', '0005_auto_20220529_1710'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visiteuruserrelation',
            options={'verbose_name': 'Relación usuarios visitantes'},
        ),
        migrations.AddField(
            model_name='usersjourney',
            name='parsed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visiteur',
            name='is_bot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visiteurjourney',
            name='parsed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='web_location',
            field=models.CharField(blank=True, choices=[('web-inicio', 'Web-Inicio'), ('screener-inicio', 'Screener-Inicio'), ('screener-market', 'Screener-Market'), ('screener-company', 'Screener-Company'), ('cartera-inicio', 'Cartera-Inicio'), ('cartera-financials', 'Cartera-Financials'), ('cartera-balance', 'Cartera-Balance'), ('private-profile', 'Private-Profile'), ('public-profile', 'Public-Profile'), ('question-inicio', 'Question-Inicio'), ('question', 'Question'), ('term-inicio', 'Term-Inicio'), ('term', 'Term'), ('blog-inicio', 'Blog-Inicio'), ('blog', 'Blog')], max_length=250),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='web_promotion_type',
            field=models.CharField(blank=True, choices=[('pop_up', 'Pop up'), ('banner', 'Big Banner'), ('list', 'List'), ('solo', 'Solo')], max_length=250),
        ),
        migrations.AlterField(
            model_name='visiteuruserrelation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='visiteuruserrelation',
            name='visiteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='seo.visiteur'),
        ),
        migrations.AlterModelTable(
            name='visiteuruserrelation',
            table='seo_users_visiteurs_relation',
        ),
        migrations.CreateModel(
            name='VisiteurTermVisited',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('model_visited', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='escritos.term')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='seo.visiteur')),
                ('visit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='seo.visiteurjourney')),
            ],
            options={
                'verbose_name': 'Term visited by visiteur',
                'db_table': 'seo_terms_visited_visiteurs',
            },
        ),
        migrations.CreateModel(
            name='VisiteurQuestionVisited',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('model_visited', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='preguntas_respuestas.question')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='seo.visiteur')),
                ('visit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='seo.visiteurjourney')),
            ],
            options={
                'verbose_name': 'Question visited by visiteur',
                'db_table': 'seo_questions_visited_visiteurs',
            },
        ),
        migrations.CreateModel(
            name='VisiteurPublicBlogVisited',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('model_visited', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='public_blog.publicblog')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='seo.visiteur')),
                ('visit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='seo.visiteurjourney')),
            ],
            options={
                'verbose_name': 'PublicBlog visited by visiteur',
                'db_table': 'seo_public_blogs_visited_visiteurs',
            },
        ),
        migrations.CreateModel(
            name='VisiteurCompanyVisited',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('model_visited', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='empresas.company')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='seo.visiteur')),
                ('visit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='seo.visiteurjourney')),
            ],
            options={
                'verbose_name': 'Company visited by visiteur',
                'db_table': 'seo_companies_visited_visiteurs',
            },
        ),
        migrations.CreateModel(
            name='UserTermVisited',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('model_visited', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='escritos.term')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='seo.usersjourney')),
            ],
            options={
                'verbose_name': 'Term visited by user',
                'db_table': 'seo_terms_visited_users',
            },
        ),
        migrations.CreateModel(
            name='UserQuestionVisited',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('model_visited', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='preguntas_respuestas.question')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='seo.usersjourney')),
            ],
            options={
                'verbose_name': 'Question visited by user',
                'db_table': 'seo_questions_visited_users',
            },
        ),
        migrations.CreateModel(
            name='UserPublicBlogVisited',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('model_visited', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='public_blog.publicblog')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='seo.usersjourney')),
            ],
            options={
                'verbose_name': 'PublicBlog visited by user',
                'db_table': 'seo_public_blogs_visited_users',
            },
        ),
        migrations.CreateModel(
            name='UserCompanyVisited',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('model_visited', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='empresas.company')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='seo.usersjourney')),
            ],
            options={
                'verbose_name': 'Company visited by user',
                'db_table': 'seo_companies_visited_users',
            },
        ),
    ]
