# Generated by Django 3.2.12 on 2022-07-11 18:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0007_auto_20220605_2147'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UsersJourney',
            new_name='UserJourney',
        ),
    ]
