# Generated by Django 3.2.12 on 2022-07-11 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0008_rename_usersjourney_userjourney'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='web_place',
            field=models.CharField(blank=True, choices=[('side', 'Side'), ('top', 'Top'), ('middle', 'Middle'), ('bottom', 'Bottom'), ('in_between', 'In between')], max_length=250),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='web_location',
            field=models.CharField(blank=True, choices=[('web-inicio', 'Web Inicio'), ('screener-inicio', 'Screener Inicio'), ('screener-market', 'Screener Market'), ('screener-company', 'Screener Company'), ('cartera-inicio', 'Cartera Inicio'), ('cartera-financials', 'Cartera Financials'), ('cartera-balance', 'Cartera Balance'), ('private-profile', 'Private Profile'), ('public-profile', 'Public Profile'), ('question-inicio', 'Question Inicio'), ('question-details', 'Question Details'), ('term-inicio', 'Term Inicio'), ('term-details', 'Term Details'), ('blog-inicio', 'Blog Inicio'), ('blog-details', 'Blog Details')], max_length=250),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='web_promotion_type',
            field=models.CharField(blank=True, choices=[('pop_up', 'Pop up'), ('banner', 'Big Banner'), ('lista', 'List'), ('solo', 'Solo')], max_length=250),
        ),
    ]
