# Generated by Django 3.2.14 on 2022-07-16 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0009_auto_20220712_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='web_location',
            field=models.CharField(blank=True, choices=[('all-web', 'Toda la web'), ('web-inicio', 'Web Inicio'), ('screener-inicio', 'Screener Inicio'), ('screener-market', 'Screener Market'), ('screener-company', 'Screener Company'), ('cartera-inicio', 'Cartera Inicio'), ('cartera-financials', 'Cartera Financials'), ('cartera-balance', 'Cartera Balance'), ('private-profile', 'Private Profile'), ('public-profile', 'Public Profile'), ('question-inicio', 'Question Inicio'), ('question-details', 'Question Details'), ('term-inicio', 'Term Inicio'), ('term-details', 'Term Details'), ('blog-inicio', 'Blog Inicio'), ('blog-details', 'Blog Details')], max_length=250),
        ),
    ]
