# Generated by Django 3.2.14 on 2022-07-25 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0010_alter_promotion_web_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='campaign_related',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='users_clicked',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='visiteurs_clicked',
        ),
        migrations.RemoveField(
            model_name='promotioncampaign',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='promotioncampaign',
            name='tags',
        ),
    ]
