# Generated by Django 3.2.12 on 2022-07-11 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recsys', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercompanyrecommended',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='usercompanyrecommended',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='usercompanyrecommended',
            name='visit',
        ),
        migrations.RemoveField(
            model_name='userproductcomplementaryrecommended',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='userproductcomplementaryrecommended',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='userproductcomplementaryrecommended',
            name='visit',
        ),
        migrations.RemoveField(
            model_name='userpromotionrecommended',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='userpromotionrecommended',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='userpromotionrecommended',
            name='visit',
        ),
        migrations.RemoveField(
            model_name='userpublicblogrecommended',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='userpublicblogrecommended',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='userpublicblogrecommended',
            name='visit',
        ),
        migrations.RemoveField(
            model_name='userquestionrecommended',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='userquestionrecommended',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='userquestionrecommended',
            name='visit',
        ),
        migrations.RemoveField(
            model_name='usertermrecommended',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='usertermrecommended',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='usertermrecommended',
            name='visit',
        ),
        migrations.RemoveField(
            model_name='visiteurcompanyrecommended',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='visiteurcompanyrecommended',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='visiteurcompanyrecommended',
            name='visit',
        ),
        migrations.RemoveField(
            model_name='visiteurproductcomplementaryrecommended',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='visiteurproductcomplementaryrecommended',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='visiteurproductcomplementaryrecommended',
            name='visit',
        ),
        migrations.RemoveField(
            model_name='visiteurpromotionrecommended',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='visiteurpromotionrecommended',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='visiteurpromotionrecommended',
            name='visit',
        ),
        migrations.RemoveField(
            model_name='visiteurpublicblogrecommended',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='visiteurpublicblogrecommended',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='visiteurpublicblogrecommended',
            name='visit',
        ),
        migrations.RemoveField(
            model_name='visiteurquestionrecommended',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='visiteurquestionrecommended',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='visiteurquestionrecommended',
            name='visit',
        ),
        migrations.RemoveField(
            model_name='visiteurtermrecommended',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='visiteurtermrecommended',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='visiteurtermrecommended',
            name='visit',
        ),
        migrations.AlterField(
            model_name='usercompanyrecommended',
            name='kind',
            field=models.CharField(choices=[('pop_up', 'Pop up'), ('banner', 'Big Banner'), ('lista', 'List'), ('solo', 'Solo')], max_length=150),
        ),
        migrations.AlterField(
            model_name='usercompanyrecommended',
            name='place',
            field=models.CharField(choices=[('web-inicio', 'Web Inicio'), ('screener-inicio', 'Screener Inicio'), ('screener-market', 'Screener Market'), ('screener-company', 'Screener Company'), ('cartera-inicio', 'Cartera Inicio'), ('cartera-financials', 'Cartera Financials'), ('cartera-balance', 'Cartera Balance'), ('private-profile', 'Private Profile'), ('public-profile', 'Public Profile'), ('question-inicio', 'Question Inicio'), ('question-details', 'Question Details'), ('term-inicio', 'Term Inicio'), ('term-details', 'Term Details'), ('blog-inicio', 'Blog Inicio'), ('blog-details', 'Blog Details')], max_length=150),
        ),
        migrations.AlterField(
            model_name='userproductcomplementaryrecommended',
            name='kind',
            field=models.CharField(choices=[('pop_up', 'Pop up'), ('banner', 'Big Banner'), ('lista', 'List'), ('solo', 'Solo')], max_length=150),
        ),
        migrations.AlterField(
            model_name='userproductcomplementaryrecommended',
            name='place',
            field=models.CharField(choices=[('web-inicio', 'Web Inicio'), ('screener-inicio', 'Screener Inicio'), ('screener-market', 'Screener Market'), ('screener-company', 'Screener Company'), ('cartera-inicio', 'Cartera Inicio'), ('cartera-financials', 'Cartera Financials'), ('cartera-balance', 'Cartera Balance'), ('private-profile', 'Private Profile'), ('public-profile', 'Public Profile'), ('question-inicio', 'Question Inicio'), ('question-details', 'Question Details'), ('term-inicio', 'Term Inicio'), ('term-details', 'Term Details'), ('blog-inicio', 'Blog Inicio'), ('blog-details', 'Blog Details')], max_length=150),
        ),
        migrations.AlterField(
            model_name='userpromotionrecommended',
            name='kind',
            field=models.CharField(choices=[('pop_up', 'Pop up'), ('banner', 'Big Banner'), ('lista', 'List'), ('solo', 'Solo')], max_length=150),
        ),
        migrations.AlterField(
            model_name='userpromotionrecommended',
            name='place',
            field=models.CharField(choices=[('web-inicio', 'Web Inicio'), ('screener-inicio', 'Screener Inicio'), ('screener-market', 'Screener Market'), ('screener-company', 'Screener Company'), ('cartera-inicio', 'Cartera Inicio'), ('cartera-financials', 'Cartera Financials'), ('cartera-balance', 'Cartera Balance'), ('private-profile', 'Private Profile'), ('public-profile', 'Public Profile'), ('question-inicio', 'Question Inicio'), ('question-details', 'Question Details'), ('term-inicio', 'Term Inicio'), ('term-details', 'Term Details'), ('blog-inicio', 'Blog Inicio'), ('blog-details', 'Blog Details')], max_length=150),
        ),
        migrations.AlterField(
            model_name='userpublicblogrecommended',
            name='kind',
            field=models.CharField(choices=[('pop_up', 'Pop up'), ('banner', 'Big Banner'), ('lista', 'List'), ('solo', 'Solo')], max_length=150),
        ),
        migrations.AlterField(
            model_name='userpublicblogrecommended',
            name='place',
            field=models.CharField(choices=[('web-inicio', 'Web Inicio'), ('screener-inicio', 'Screener Inicio'), ('screener-market', 'Screener Market'), ('screener-company', 'Screener Company'), ('cartera-inicio', 'Cartera Inicio'), ('cartera-financials', 'Cartera Financials'), ('cartera-balance', 'Cartera Balance'), ('private-profile', 'Private Profile'), ('public-profile', 'Public Profile'), ('question-inicio', 'Question Inicio'), ('question-details', 'Question Details'), ('term-inicio', 'Term Inicio'), ('term-details', 'Term Details'), ('blog-inicio', 'Blog Inicio'), ('blog-details', 'Blog Details')], max_length=150),
        ),
        migrations.AlterField(
            model_name='userquestionrecommended',
            name='kind',
            field=models.CharField(choices=[('pop_up', 'Pop up'), ('banner', 'Big Banner'), ('lista', 'List'), ('solo', 'Solo')], max_length=150),
        ),
        migrations.AlterField(
            model_name='userquestionrecommended',
            name='place',
            field=models.CharField(choices=[('web-inicio', 'Web Inicio'), ('screener-inicio', 'Screener Inicio'), ('screener-market', 'Screener Market'), ('screener-company', 'Screener Company'), ('cartera-inicio', 'Cartera Inicio'), ('cartera-financials', 'Cartera Financials'), ('cartera-balance', 'Cartera Balance'), ('private-profile', 'Private Profile'), ('public-profile', 'Public Profile'), ('question-inicio', 'Question Inicio'), ('question-details', 'Question Details'), ('term-inicio', 'Term Inicio'), ('term-details', 'Term Details'), ('blog-inicio', 'Blog Inicio'), ('blog-details', 'Blog Details')], max_length=150),
        ),
        migrations.AlterField(
            model_name='usertermrecommended',
            name='kind',
            field=models.CharField(choices=[('pop_up', 'Pop up'), ('banner', 'Big Banner'), ('lista', 'List'), ('solo', 'Solo')], max_length=150),
        ),
        migrations.AlterField(
            model_name='usertermrecommended',
            name='place',
            field=models.CharField(choices=[('web-inicio', 'Web Inicio'), ('screener-inicio', 'Screener Inicio'), ('screener-market', 'Screener Market'), ('screener-company', 'Screener Company'), ('cartera-inicio', 'Cartera Inicio'), ('cartera-financials', 'Cartera Financials'), ('cartera-balance', 'Cartera Balance'), ('private-profile', 'Private Profile'), ('public-profile', 'Public Profile'), ('question-inicio', 'Question Inicio'), ('question-details', 'Question Details'), ('term-inicio', 'Term Inicio'), ('term-details', 'Term Details'), ('blog-inicio', 'Blog Inicio'), ('blog-details', 'Blog Details')], max_length=150),
        ),
        migrations.AlterField(
            model_name='visiteurcompanyrecommended',
            name='kind',
            field=models.CharField(choices=[('pop_up', 'Pop up'), ('banner', 'Big Banner'), ('lista', 'List'), ('solo', 'Solo')], max_length=150),
        ),
        migrations.AlterField(
            model_name='visiteurcompanyrecommended',
            name='place',
            field=models.CharField(choices=[('web-inicio', 'Web Inicio'), ('screener-inicio', 'Screener Inicio'), ('screener-market', 'Screener Market'), ('screener-company', 'Screener Company'), ('cartera-inicio', 'Cartera Inicio'), ('cartera-financials', 'Cartera Financials'), ('cartera-balance', 'Cartera Balance'), ('private-profile', 'Private Profile'), ('public-profile', 'Public Profile'), ('question-inicio', 'Question Inicio'), ('question-details', 'Question Details'), ('term-inicio', 'Term Inicio'), ('term-details', 'Term Details'), ('blog-inicio', 'Blog Inicio'), ('blog-details', 'Blog Details')], max_length=150),
        ),
        migrations.AlterField(
            model_name='visiteurproductcomplementaryrecommended',
            name='kind',
            field=models.CharField(choices=[('pop_up', 'Pop up'), ('banner', 'Big Banner'), ('lista', 'List'), ('solo', 'Solo')], max_length=150),
        ),
        migrations.AlterField(
            model_name='visiteurproductcomplementaryrecommended',
            name='place',
            field=models.CharField(choices=[('web-inicio', 'Web Inicio'), ('screener-inicio', 'Screener Inicio'), ('screener-market', 'Screener Market'), ('screener-company', 'Screener Company'), ('cartera-inicio', 'Cartera Inicio'), ('cartera-financials', 'Cartera Financials'), ('cartera-balance', 'Cartera Balance'), ('private-profile', 'Private Profile'), ('public-profile', 'Public Profile'), ('question-inicio', 'Question Inicio'), ('question-details', 'Question Details'), ('term-inicio', 'Term Inicio'), ('term-details', 'Term Details'), ('blog-inicio', 'Blog Inicio'), ('blog-details', 'Blog Details')], max_length=150),
        ),
        migrations.AlterField(
            model_name='visiteurpromotionrecommended',
            name='kind',
            field=models.CharField(choices=[('pop_up', 'Pop up'), ('banner', 'Big Banner'), ('lista', 'List'), ('solo', 'Solo')], max_length=150),
        ),
        migrations.AlterField(
            model_name='visiteurpromotionrecommended',
            name='place',
            field=models.CharField(choices=[('web-inicio', 'Web Inicio'), ('screener-inicio', 'Screener Inicio'), ('screener-market', 'Screener Market'), ('screener-company', 'Screener Company'), ('cartera-inicio', 'Cartera Inicio'), ('cartera-financials', 'Cartera Financials'), ('cartera-balance', 'Cartera Balance'), ('private-profile', 'Private Profile'), ('public-profile', 'Public Profile'), ('question-inicio', 'Question Inicio'), ('question-details', 'Question Details'), ('term-inicio', 'Term Inicio'), ('term-details', 'Term Details'), ('blog-inicio', 'Blog Inicio'), ('blog-details', 'Blog Details')], max_length=150),
        ),
        migrations.AlterField(
            model_name='visiteurpublicblogrecommended',
            name='kind',
            field=models.CharField(choices=[('pop_up', 'Pop up'), ('banner', 'Big Banner'), ('lista', 'List'), ('solo', 'Solo')], max_length=150),
        ),
        migrations.AlterField(
            model_name='visiteurpublicblogrecommended',
            name='place',
            field=models.CharField(choices=[('web-inicio', 'Web Inicio'), ('screener-inicio', 'Screener Inicio'), ('screener-market', 'Screener Market'), ('screener-company', 'Screener Company'), ('cartera-inicio', 'Cartera Inicio'), ('cartera-financials', 'Cartera Financials'), ('cartera-balance', 'Cartera Balance'), ('private-profile', 'Private Profile'), ('public-profile', 'Public Profile'), ('question-inicio', 'Question Inicio'), ('question-details', 'Question Details'), ('term-inicio', 'Term Inicio'), ('term-details', 'Term Details'), ('blog-inicio', 'Blog Inicio'), ('blog-details', 'Blog Details')], max_length=150),
        ),
        migrations.AlterField(
            model_name='visiteurquestionrecommended',
            name='kind',
            field=models.CharField(choices=[('pop_up', 'Pop up'), ('banner', 'Big Banner'), ('lista', 'List'), ('solo', 'Solo')], max_length=150),
        ),
        migrations.AlterField(
            model_name='visiteurquestionrecommended',
            name='place',
            field=models.CharField(choices=[('web-inicio', 'Web Inicio'), ('screener-inicio', 'Screener Inicio'), ('screener-market', 'Screener Market'), ('screener-company', 'Screener Company'), ('cartera-inicio', 'Cartera Inicio'), ('cartera-financials', 'Cartera Financials'), ('cartera-balance', 'Cartera Balance'), ('private-profile', 'Private Profile'), ('public-profile', 'Public Profile'), ('question-inicio', 'Question Inicio'), ('question-details', 'Question Details'), ('term-inicio', 'Term Inicio'), ('term-details', 'Term Details'), ('blog-inicio', 'Blog Inicio'), ('blog-details', 'Blog Details')], max_length=150),
        ),
        migrations.AlterField(
            model_name='visiteurtermrecommended',
            name='kind',
            field=models.CharField(choices=[('pop_up', 'Pop up'), ('banner', 'Big Banner'), ('lista', 'List'), ('solo', 'Solo')], max_length=150),
        ),
        migrations.AlterField(
            model_name='visiteurtermrecommended',
            name='place',
            field=models.CharField(choices=[('web-inicio', 'Web Inicio'), ('screener-inicio', 'Screener Inicio'), ('screener-market', 'Screener Market'), ('screener-company', 'Screener Company'), ('cartera-inicio', 'Cartera Inicio'), ('cartera-financials', 'Cartera Financials'), ('cartera-balance', 'Cartera Balance'), ('private-profile', 'Private Profile'), ('public-profile', 'Public Profile'), ('question-inicio', 'Question Inicio'), ('question-details', 'Question Details'), ('term-inicio', 'Term Inicio'), ('term-details', 'Term Details'), ('blog-inicio', 'Blog Inicio'), ('blog-details', 'Blog Details')], max_length=150),
        ),
    ]
