# Generated by Django 3.2.12 on 2022-03-07 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicblog',
            options={'ordering': ['-id'], 'verbose_name': 'Public blog post'},
        ),
    ]
