# Generated by Django 3.2.12 on 2022-03-08 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public_blog', '0002_alter_publicblog_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicblog',
            name='has_been_scheduled',
        ),
    ]
