# Generated by Django 3.2.12 on 2022-04-15 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_blog', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicblog',
            name='non_thumbnail_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='publicblog',
            name='slug',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='publicblog',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='publicblogasnewsletter',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='writterprofile',
            name='facebook',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='writterprofile',
            name='host_name',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='writterprofile',
            name='insta',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='writterprofile',
            name='linkedin',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='writterprofile',
            name='tiktok',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='writterprofile',
            name='twitter',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='writterprofile',
            name='youtube',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
