# Generated by Django 3.2.12 on 2022-03-09 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_blog', '0003_remove_publicblog_has_been_scheduled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicblog',
            old_name='publishing_date',
            new_name='date_to_publish',
        ),
        migrations.AddField(
            model_name='publicblogasnewsletter',
            name='date_to_send',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publicblogasnewsletter',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
