# Generated by Django 3.2.12 on 2022-05-28 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_blog', '0004_auto_20220429_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicblog',
            name='slug',
            field=models.SlugField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='publicblog',
            name='title',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
