# Generated by Django 3.2.12 on 2022-03-10 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public_blog', '0004_auto_20220309_0054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicblog',
            options={'ordering': ['total_views'], 'verbose_name': 'Public blog post'},
        ),
    ]
