# Generated by Django 3.2.12 on 2022-03-13 00:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public_blog', '0006_auto_20220312_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicblogasnewsletter',
            name='despedida',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='publicblogasnewsletter',
            name='introduction',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
