# Generated by Django 3.2.12 on 2022-03-18 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public_blog', '0009_auto_20220317_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailpublicblog',
            name='email_related',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_related', to='public_blog.publicblogasnewsletter'),
        ),
        migrations.AlterField(
            model_name='publicblogasnewsletter',
            name='blog_related',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_blog_newsletter', to='public_blog.publicblog'),
        ),
    ]
