AAPL = {"id":7,
"ticker":"AAPL",
"name":"Apple Inc.",
"sector_id":1,
"website":"http://www.apple.com",
"state":"CALIFORNIA",
"country_id":1,
"ceo":"Mr. Timothy Cook",
"image":"https://logo.clearbit.com/apple.com",
"city":"Cupertino",
"employees":"154000",
"address":"1 Apple Park Way",
"zip_code":"95014",
"cik":"0000320193",
"cusip":"037833100",
"isin":"US0378331005",
"description":"Apple Inc. Diseños, fabricantes y mercados Smartphones, computadoras personales, tabletas, wearables y accesorios en todo el mundo. También vende varios servicios relacionados. La compañía ofrece iPhone, una línea de teléfonos inteligentes; Mac, una línea de computadoras personales; iPad, una línea de tabletas multiusos; y los wearables, el hogar y los accesorios que comprenden airpods, Apple TV, Apple Watch, Beats Products, HomePod, iPod Touch y otros accesorios de marca de manzana y de terceros. También proporciona servicios de soporte AppleCare; Servicios de Tienda de Servicios en Cloud; y opera varias plataformas, incluida la tienda de aplicaciones, que permiten a los clientes descubrir y descargar aplicaciones y contenido digital, como libros, música, videos, juegos y podcasts. Además, la compañía ofrece diversos servicios, como Apple Arcade, un servicio de suscripción al juego; Apple Music, que ofrece a los usuarios una experiencia auditiva curada con estaciones de radio bajo demanda; Apple News +, un servicio de noticias de suscripción y revista; Apple TV +, que ofrece contenido original exclusivo; Tarjeta de Apple, una tarjeta de crédito de marca compartida; y Apple Pay, un servicio de pago sin efectivo, así como licencias de su propiedad intelectual. La compañía sirve a los consumidores, y pequeñas y medianas empresas; y la educación, la empresa y los mercados gubernamentales. Vende y ofrece aplicaciones de terceros para sus productos a través de la App Store. La compañía también vende sus productos a través de sus tiendas minoristas y en línea, y fuerza de ventas directa; y portadores de red celulares de terceros, mayoristas, minoristas y revendedores. Apple Inc. se fundó en 1977 y tiene su sede en Cupertino, California. ",
"ipoDate":"1980-12-12",
"remote_image_imagekit":"https://ik.imagekit.io/invfin/companies/Technology/AAPL.webp?tr=h-300%2Cw-300&ik-sdk-version=python-2.2.8"
}