# Generated by Django 3.2.12 on 2022-03-06 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escritos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsRelatedToResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_to_delete', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='term_to_delete', to='escritos.term')),
                ('term_to_keep', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='term_to_keep', to='escritos.term')),
            ],
            options={
                'verbose_name': 'Terms to resume',
                'db_table': 'terms_to_resume',
            },
        ),
        migrations.DeleteModel(
            name='TermsOldUrls',
        ),
    ]
