# Generated by Django 3.2.12 on 2022-03-28 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('general', '0001_initial'),
        ('seo', '0001_initial'),
        ('escritos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='termsharedhistorial',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='termscomment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='termscomment',
            name='content_related',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments_related', to='escritos.term'),
        ),
        migrations.AddField(
            model_name='termcorrection',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='termcorrection',
            name='reviwed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrector', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='termcorrection',
            name='term_content_related',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='escritos.termcontent'),
        ),
        migrations.AddField(
            model_name='termcontent',
            name='term_related',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='term_content_parts', to='escritos.term'),
        ),
        migrations.AddField(
            model_name='term',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='term',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='general.category'),
        ),
        migrations.AddField(
            model_name='term',
            name='downvotes',
            field=models.ManyToManyField(blank=True, related_name='user_downvote_term', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='term',
            name='meta_information',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='seo.metaparametershistorial'),
        ),
        migrations.AddField(
            model_name='term',
            name='tags',
            field=models.ManyToManyField(blank=True, to='general.Tag'),
        ),
        migrations.AddField(
            model_name='term',
            name='upvotes',
            field=models.ManyToManyField(blank=True, related_name='user_upvote_term', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='favoritestermslist',
            name='term',
            field=models.ManyToManyField(blank=True, to='escritos.Term'),
        ),
        migrations.AddField(
            model_name='favoritestermslist',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favorites_terms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='favoritestermshistorial',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='escritos.term'),
        ),
        migrations.AddField(
            model_name='favoritestermshistorial',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
