# Generated by Django 3.2.12 on 2022-03-07 03:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('escritos', '0002_auto_20220306_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='in_text_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='term',
            name='non_thumbnail_url',
            field=models.CharField(blank=True, max_length=99999, null=True),
        ),
        migrations.CreateModel(
            name='FavoritesTermsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.ManyToManyField(blank=True, to='escritos.Term')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favorites_terms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lista de términos favoritos',
                'verbose_name_plural': 'Lista de términos favoritos',
                'db_table': 'favorites_terms_list',
            },
        ),
        migrations.CreateModel(
            name='FavoritesTermsHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('added', models.BooleanField(default=False)),
                ('removed', models.BooleanField(default=False)),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='escritos.term')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Término favorito',
                'verbose_name_plural': 'Términos favoritos',
                'db_table': 'favorites_terms_historial',
            },
        ),
    ]
