# Generated by Django 3.2.12 on 2022-04-15 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escritos', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='non_thumbnail_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='term',
            name='slug',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='term',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
