# Generated by Django 3.2.12 on 2022-04-29 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escritos', '0003_auto_20220415_0001'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TermSharedHistorial',
        ),
    ]
