# Generated by Django 3.2.12 on 2022-03-08 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escritos', '0003_auto_20220307_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termcontent',
            name='term_related',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='term_content_parts', to='escritos.term'),
        ),
    ]
