# Generated by Django 3.2.12 on 2022-03-10 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escritos', '0004_alter_termcontent_term_related'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='term',
            options={'ordering': ['total_views'], 'verbose_name': 'Término del glosario'},
        ),
    ]
