# Generated by Django 3.2.12 on 2022-03-05 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField()),
                ('quarter', models.IntegerField(default=1)),
                ('current_period', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Superinvestor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=600000, null=True)),
                ('fund_name', models.CharField(blank=True, max_length=600000, null=True)),
                ('info_accronym', models.CharField(blank=True, max_length=600000, null=True)),
                ('slug', models.CharField(blank=True, max_length=600000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SuperinvestorHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.FloatField(blank=True, null=True)),
                ('num_shares', models.FloatField(blank=True, null=True)),
                ('reported_price', models.FloatField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empresas.company')),
                ('period_related', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='super_investors.period')),
                ('superinvestor_related', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='super_investors.superinvestor')),
            ],
        ),
        migrations.CreateModel(
            name='SuperinvestorActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage_added', models.FloatField(blank=True, null=True)),
                ('share_change', models.FloatField(blank=True, null=True)),
                ('portfolio_change', models.FloatField(blank=True, null=True)),
                ('is_new', models.BooleanField(default=False)),
                ('movement', models.PositiveIntegerField(choices=[(1, 'Compra'), (2, 'Venta')])),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empresas.company')),
                ('period_related', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='super_investors.period')),
                ('superinvestor_related', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='super_investors.superinvestor')),
            ],
        ),
    ]
