# Generated by Django 3.2.12 on 2022-06-01 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0007_institutionalorganization_topinstitutionalownership'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField(blank=True, null=True)),
                ('period', models.IntegerField(blank=True, choices=[(1, '1 Quarter'), (2, '2 Quarter'), (3, '3 Quarter'), (4, '4 Quarter')], null=True)),
            ],
            options={
                'verbose_name': 'Period',
                'verbose_name_plural': 'Periods',
                'db_table': 'assets_periods',
            },
        ),
        migrations.CreateModel(
            name='Superinvestor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=600000, null=True)),
                ('fund_name', models.CharField(blank=True, max_length=600000, null=True)),
                ('info_accronym', models.CharField(blank=True, max_length=600000, null=True)),
                ('slug', models.CharField(blank=True, max_length=600000, null=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('has_error', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Superinvestor',
                'verbose_name_plural': 'Superinvestors',
                'db_table': 'superinvestors',
            },
        ),
        migrations.CreateModel(
            name='SuperinvestorActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage_share_change', models.FloatField(blank=True, null=True)),
                ('share_change', models.FloatField(blank=True, null=True)),
                ('portfolio_change', models.FloatField(blank=True, null=True)),
                ('is_new', models.BooleanField(default=False)),
                ('movement', models.PositiveIntegerField(choices=[(1, 'Compra'), (2, 'Venta')])),
                ('company_name', models.TextField(blank=True, null=True)),
                ('not_registered_company', models.BooleanField(default=False)),
                ('need_verify_company', models.BooleanField(default=False)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empresas.company')),
                ('period_related', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='super_investors.period')),
                ('superinvestor_related', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='super_investors.superinvestor')),
            ],
        ),
    ]
