# Generated by Django 3.2.12 on 2022-03-14 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_investors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='superinvestor',
            name='last_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='superinvestor',
            name='updated',
            field=models.BooleanField(default=False),
        ),
    ]
