# Generated by Django 3.2.12 on 2022-06-01 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('super_investors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='superinvestoractivity',
            options={'verbose_name': 'Superinvestor activity', 'verbose_name_plural': 'Superinvestors activity'},
        ),
        migrations.AlterModelTable(
            name='superinvestoractivity',
            table='superinvestors_activity',
        ),
    ]
