# Generated by Django 3.2.12 on 2022-06-01 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_investors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='superinvestoractivity',
            options={'verbose_name': 'Superinvestor activity', 'verbose_name_plural': 'Superinvestors activity'},
        ),
        migrations.AlterField(
            model_name='superinvestoractivity',
            name='movement',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Compra'), (2, 'Venta')], null=True),
        ),
        migrations.AlterModelTable(
            name='superinvestoractivity',
            table='superinvestors_activity',
        ),
    ]
