# Generated by Django 3.2.12 on 2022-03-21 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_investors', '0002_auto_20220314_1617'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='period',
            options={'verbose_name': 'Period', 'verbose_name_plural': 'Periods'},
        ),
        migrations.AlterModelOptions(
            name='superinvestor',
            options={'verbose_name': 'Superinvestor', 'verbose_name_plural': 'Superinvestors'},
        ),
        migrations.RemoveField(
            model_name='period',
            name='current_period',
        ),
        migrations.RemoveField(
            model_name='period',
            name='quarter',
        ),
        migrations.AddField(
            model_name='period',
            name='period',
            field=models.IntegerField(blank=True, choices=[(1, '1 Quarter'), (2, '2 Quarter'), (3, '3 Quarter'), (4, '4 Quarter')], null=True),
        ),
        migrations.AlterField(
            model_name='period',
            name='year',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='period',
            table='assets_periods',
        ),
        migrations.AlterModelTable(
            name='superinvestor',
            table='superinvestors',
        ),
        migrations.DeleteModel(
            name='SuperinvestorHolding',
        ),
    ]
