# Generated by Django 3.2.12 on 2022-06-01 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_investors', '0002_auto_20220601_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superinvestoractivity',
            name='movement',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Compra'), (2, 'Venta')], null=True),
        ),
    ]
