# Generated by Django 3.2.12 on 2022-06-01 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('super_investors', '0002_auto_20220601_2159'),
        ('super_investors', '0003_alter_superinvestoractivity_movement'),
    ]

    operations = [
    ]
