# Generated by Django 3.2.12 on 2022-06-03 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_investors', '0003_auto_20220603_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='superinvestor',
            name='image',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
