# Generated by Django 3.2.12 on 2022-06-08 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0007_institutionalorganization_topinstitutionalownership'),
        ('super_investors', '0003_auto_20220603_1956'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='period',
            options={'ordering': ['period', 'year'], 'verbose_name': 'Period', 'verbose_name_plural': 'Periods'},
        ),
        migrations.AddField(
            model_name='superinvestor',
            name='image',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='superinvestoractivity',
            name='superinvestor_related',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions', to='super_investors.superinvestor'),
        ),
        migrations.CreateModel(
            name='SuperinvestorHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.TextField(blank=True, null=True)),
                ('portfolio_change', models.FloatField(blank=True, null=True)),
                ('movement', models.CharField(blank=True, max_length=500, null=True)),
                ('not_registered_company', models.BooleanField(default=False)),
                ('need_verify_company', models.BooleanField(default=False)),
                ('shares', models.FloatField(blank=True, null=True)),
                ('reported_price', models.FloatField(blank=True, null=True)),
                ('portfolio_weight', models.FloatField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empresas.company')),
                ('period_related', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='super_investors.period')),
                ('superinvestor_related', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='super_investors.superinvestor')),
            ],
            options={
                'verbose_name': 'Superinvestor history',
                'verbose_name_plural': 'Superinvestors history',
                'db_table': 'superinvestors_history',
            },
        ),
    ]
