# Generated by Django 3.2.12 on 2022-06-03 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('super_investors', '0004_superinvestor_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='period',
            options={'ordering': ['period', 'year'], 'verbose_name': 'Period', 'verbose_name_plural': 'Periods'},
        ),
        migrations.AddField(
            model_name='superinvestoractivity',
            name='reported_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='superinvestoractivity',
            name='shares',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='superinvestoractivity',
            name='superinvestor_related',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions', to='super_investors.superinvestor'),
        ),
    ]
