# Generated by Django 3.2.14 on 2022-07-24 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0007_period'),
        ('super_investors', '0007_auto_20220612_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superinvestoractivity',
            name='period_related',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='general.period'),
        ),
        migrations.AlterField(
            model_name='superinvestorhistory',
            name='period_related',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='general.period'),
        ),
        migrations.DeleteModel(
            name='Period',
        ),
    ]
